### ISSUE TITLE
Installation on ubuntu 24.04 Wayland - fails

### ISSUE THREAD

**Issue by able2doit** [federico-terzi/espanso#2119] opened 2024-11-03 12:41 UTC
### Description

The instruction should read "sudo dpkg -i ./espanso-debian-wayland-amd64.deb" instead of "sudo apt install ./espanso-debian-wayland-amd64.deb".

### Motivation

To enable installation.

### Alternatives

None

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment] 2024-11-03 13:36
Although you may be technically correct, and I'm not an expert, a search of the Ubuntu forums supports the use of `apt` over `dpkg` because the former will resolve dependencies automatically. Probably simpler to leave it as it is? Do you think `dpkg` works better?

**Comment by Lancelotmay** [comment] 2024-12-04 12:16
apt should be the recommend way now. 
In my case, apt works good to get espanso installed.
I believe the issue is not related to the installation, but [#1793 ](https://github.com/espanso/espanso/issues/1793)


> Although you may be technically correct, and I'm not an expert, a search of the Ubuntu forums supports the use of `apt` over `dpkg` because the former will resolve dependencies automatically. Probably simpler to leave it as it is? Do you think `dpkg` works better?

**Comment by smeech** [comment] 2024-12-04 12:24
> apt should be the recommend way now.

Thank you. As I haven't received a reply from @able2doit, to explain their assertion, I'll take this opportunity to close the Issue, although am happy to reopen it if necessary.

**Closed as completed by smeech** 2024-12-04 12:24 UTC
Labels: enhancement, needs-triage
