### ISSUE TITLE
The maximum length of a "regex match" is set to 30 characters

### ISSUE THREAD

**Issue by cesarve77** [federico-terzi/espanso#2006] opened 2024-07-09 04:32 UTC
### Description

I am planing to create a LLM extension. something like:
:gpt give ideas for a birthday invitation.

But I am limited to 30 chars, which is not enough for most prompts

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment] 2024-07-09 10:59
Duplicate of #1766 - you may wish to add further comments there.

The best workaround for the time being is probably to copy the text into the clipboard, and then invoke an Espanso trigger to make use of it via the [`clipboard` extension](https://espanso.org/docs/matches/extensions/#clipboard-extension).

**Closed as completed** 2024-07-09 10:59 UTC
