### ISSUE TITLE
Windows: Espanso breaks the Alt numpad input method for special characters

### ISSUE THREAD

**Issue by e-r-n-i-e** [federico-terzi/espanso#1151] opened 2022-06-24 08:41 UTC
**Describe the bug**
When Espanso is running it is impossible to use for example Alt+0169 (using the numpad) to get the charachter "©".

**To Reproduce**
1. Do NOT Launch Espanso – exit it if it is running
2. Hold the Alt key and press 0 1 6 9 using the numpad in your favorite editor. A "©" should appear.
3. Launch Espanso and repeat step 2 (it does not work)
4. Disable Espanso and repeat step 2 (it still does not work)
5. Exit Espanso and repeat step 2 (it works again)

**Expected behavior**
Alt+0169 (Numpad) should create a "©".

**Setup information**
- OS: Windows 10-21H2
- Version: espanso 2.1.5-beta

**Comment by federico-terzi** [comment] 2022-07-02 11:38
This is a duplicate of https://github.com/federico-terzi/espanso/issues/988, I'm closing this one in favor of the other one. Feel free to continue the discussion there :)

**Closed by federico-terzi** 2022-07-02 11:38 UTC
Labels: bug
