### ISSUE TITLE
Not working in Qt Linguist

### ISSUE THREAD

**Issue by Vistaus** [federico-terzi/espanso#768] opened 2021-10-08 15:37 UTC
Whenever I try to use Espanso in Qt Linguist, the replacement text doesn't show. I type the trigger, the trigger dissapears and the replacement text is nowhere to be found. It does copy the replacement text to the clipboard, however.

It's a weird issue 'cause my entire desktop and even my web browser is Qt-based and I don't have this issue in any other Qt desktop item/app.

**Comment by federico-terzi** [comment] 2021-10-08 17:24
Hey @Vistaus,

Thanks for reporting this issue! Usually, that is caused by espanso not using the "right" paste shortcut in those apps. What shortcut do you use to paste some text into Qt Linguist? (i.e. CTRL+C? Shift+Insert?)

Cheers :)

**Comment by Vistaus** [comment] 2021-10-08 17:48
Thanks. I tried the fast inject mode, but it doesn't make any difference whatsoever.

**Comment by federico-terzi** [comment] 2021-10-10 08:59
@Vistaus You're welcome :) Hopefully, we'll get this one working as well

**Comment by Vistaus** [comment] 2022-01-02 13:33
It seems to be working now, at least in Linguist+Espanso on Wayland. 🙂

**Comment by federico-terzi** [comment] 2022-01-02 20:16
@Vistaus Nice! Thanks for letting me know :) I'm closing this issue for now, feel free to reopen if the problem reappears

**Closed by federico-terzi** 2022-01-02 20:16 UTC
Labels: bug, Linux
