### ISSUE TITLE
macOS: espanso fails to load on re-login

### ISSUE THREAD

**Issue by auxbuss** [federico-terzi/espanso#1912] opened 2024-03-23 09:30 UTC
**Problem:** espanso no longer performs substitutions after logging out of a user and then logging back in (to the same uaser)

**To Reproduce**
1. Load espanso manually e.g. using Spotlight
2. This loads three espanso processes
![Screenshot 2024-03-23 at 09 32 39](https://github.com/espanso/espanso/assets/82220/b4294cf4-ee81-4275-bccc-63bf74c228d1)
3. espanso substitutions works as expected
4. Logout and login again (to the same user)
5. Note that espanso substitutions no longer work
6. Note that only espanso daemon is loaded, and process id is same as above)
![Screenshot 2024-03-23 at 09 35 14](https://github.com/espanso/espanso/assets/82220/82540194-090a-4d6a-9c41-7f863173bc8c)
7. kill -9 espanso daemon
8. Load espanso manually (same as (1) above)
9. espanso substitutions works as expected

Notes: com.federicoterzi.espanso.plist exists in ~/Library/LaunchAgents

**Expected behavior**
I'd expect espanso to perform substitutions, as normal.

**Logs**
Please advise at what point you require the log to be taken.

**Setup information**
- OS: macOS 14.4 (Sonoma)
- Version: espanso 2.2.1

**Comment by smeech** [comment] 2024-03-23 10:50
Possible duplicate of #1492, #721.

**Closed as completed** 2024-03-27 08:58 UTC
Labels: bug, MacOS

**Comment by smeech** [comment] 2024-03-27 10:07
Thank you for closing.
