### ISSUE TITLE
How do I send an "enter" ?

### ISSUE THREAD

**Issue by xircon** [federico-terzi/espanso#121] opened 2019-11-16 22:49 UTC
E.g.:
```
## Pacman
  - trigger: "syuu"
    replace: "sudo pacman -Syyuu"
```
Press enter after, to run the command? tried \n \r.

**Comment by federico-terzi** [comment] 2019-11-17 13:34
Hi @xircon,
At the moment, this is a tricky thing to do on Linux as I never thought about this use case.

An option would be to use the Inject backend ( instead of Clipboard, the default one on linux ) into an Application-specific configuration for your terminal. At that point, using \n at the end of the replace field would trigger an enter.

You will find some instructions on the documentation about Configuration.

Thanks for your feedback

**Comment by m4mum** [comment] 2019-12-10 21:15
@federico-terzi 
App specific configuration may be of little use.

e.g. In browser one tab IM (WhatsApp etc, other tab - email, 3rd tab Docs). One may need different behaviour 

Ex.   :test ->  Hello <enter> World <enter> on IM. And \n on other tabs! :)

**Comment by federico-terzi** [comment] 2019-12-11 18:14
Hi @m4mum,
I'm not really sure I understood your point, app-specific configs are already available: https://espanso.org/docs/configuration/#application-specific-configurations 

Cheers

**Comment by m4mum** [comment] 2019-12-11 18:38
Hi @Federico-Terzi/Espanso

A sample demo of config for enter/return on linux (& other os) will be great

Raxit

**Comment by federico-terzi** [comment] 2019-12-12 08:29
Hi @m4mum,
I'm sorry, I didn't understand your first message properly. Espanso currently does not support sending 'enter' after deliberately. I may add this possibility in the future though.

Thanks for your help

**Comment by federico-terzi** [comment] 2020-05-10 14:38
Hey,
I'm going to close this issue as now you can just add "\n" at the end of the replacement and that should work as intended.
Cheers :)

**Closed by federico-terzi** 2020-05-10 14:38 UTC

**Comment by m4mum** [comment] 2020-05-10 18:52
Hey

Will check, In lockdown, no apple service open here, may take few days for
me to check

Stay Safe

Raxit
