### ISSUE TITLE
Weird tiny, unusable, blocking mid-screen box / popup / widget apparing since espanso upgrade on Ubuntu 22.04.3 / wayland

### ISSUE THREAD

**Issue by bentolor** [federico-terzi/espanso#1826] opened 2024-01-26 12:38 UTC
**Describe the bug**
After upgrading from an older espanso version, on service start a weird graphic box is rendered. On clicking it, some colorful dots are rendered below. (see screenshot).

The start notification popup renders succesfully, though.

No interaction is possible, hence it also blocks my left and top bars.

**To Reproduce**
1. Just start espanso

**Expected behavior**
Espanso should be invisible or render as an icon inside menu bar.

**Screenshots**
![grafik](https://github.com/espanso/espanso/assets/588260/1c5a9b5e-4fa4-4353-bd0e-7ba7b1664fe9)

**Logs**
```
 ~/.c/e/config  espanso log                                                                                                                                                                                         Fr 26 Jan 2024 13:32:51 CET
13:31:52 [daemon(3013298)] [INFO] reading configs from: "/home/ben/.config/espanso"
13:31:52 [daemon(3013298)] [INFO] reading packages from: "/home/ben/.config/espanso/match/packages"
13:31:52 [daemon(3013298)] [INFO] using runtime dir: "/home/ben/.cache/espanso"
13:31:52 [daemon(3013298)] [INFO] system info: Ubuntu v22.04 - kernel: 5.15.0-91-generic
13:31:52 [daemon(3013298)] [INFO] watching for changes in path: "/home/ben/.config/espanso"
13:31:52 [daemon(3013298)] [INFO] espanso version: 2.2.1
13:31:52 [daemon(3013298)] [INFO] spawning the worker process...
13:31:52 [daemon(3013298)] [INFO] binded to IPC unix socket: /home/ben/.cache/espanso/espansodaemonv2.sock
13:31:52 [worker(3013305)] [INFO] reading configs from: "/home/ben/.config/espanso"
13:31:52 [worker(3013305)] [INFO] reading packages from: "/home/ben/.config/espanso/match/packages"
13:31:52 [worker(3013305)] [INFO] using runtime dir: "/home/ben/.cache/espanso"
13:31:52 [worker(3013305)] [INFO] system info: Ubuntu v22.04 - kernel: 5.15.0-91-generic
13:31:52 [worker(3013305)] [INFO] using WaylandAppInfoProvider
13:31:52 [worker(3013305)] [INFO] binded to IPC unix socket: /home/ben/.cache/espanso/espansoworkerv2.sock
13:31:52 [worker(3013305)] [INFO] monitoring the status of the daemon process
13:31:52 [worker(3013305)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de, V=, O=]
13:31:52 [worker(3013305)] [INFO] using EVDEVSource
13:31:52 [worker(3013305)] [INFO] Querying modifier status...
13:31:52 [worker(3013305)] [INFO] inject module will use this keyboard layout: [R=, M=, L=de, V=, O=]
13:31:52 [worker(3013305)] [INFO] using EVDEVInjector
13:31:52 [worker(3013305)] [INFO] using WaylandFallbackClipboard
```

**Setup information**
- OS: What OS are you using?: Ubuntu 22.04.3 LTS
- Version: 2.2.1 wayland via .deb

**Comment by AucaCoyan** [comment] 2024-01-26 18:57
Wow, that's very weird. Thanks for submitting!.
I have no idea how to start debugging this, but we'll check it out

**Comment by morgan-dgk** [comment] 2024-01-26 19:05
Probably related to #1776.

**Comment by bentolor** [comment] 2024-01-27 11:33
Thanks for your feedback, @AucaCoyan and @morgan-dgk !

I saw #1776 before, but felt it might be something different. Honestly: I do not know what/how this sync window would look like.

I deem Ubuntu 22.04 LTS such a popular choice that I wondered: "Is it me (my install)?". Please let me know if I can provide something to support.

**Comment by xeruf** [comment] 2024-01-30 15:20
Having that same issue, quite annoying. Also using Wayland (Sway).

**Comment by 4ntsu** [comment] 2024-01-31 18:06
Just wanted to point out this was also reported in #1722 and #1619. 

I was having the same problem (Arch, Gnome, Wayland, Espanso v2.2.1), and the "solution" for me was to downgrade to v2.1.8, which does not present this little window, and as a bonus can correctly detect when the keyboard layout is changed (v2.2.1 couldn't).

**Comment by readtedium** [comment] 2024-02-02 22:08
Confirming I’m also seeing this, is a small annoyance I have to move in PaperWM on Gnome. Should note that it usually appears with the [Wayland to X Recording Bridge](https://invent.kde.org/system/xwaylandvideobridge) for me. Using Nobara Linux with 6.7.1 kernel.

Looks like this for me:

![Screenshot from 2024-02-02 17-09-45](https://github.com/espanso/espanso/assets/470216/215829ff-ec4a-470d-a051-41144336c0d6)

**Comment by Steve-V** [comment] 2024-02-06 02:24
Confirming it also happens on Fedora 39 Wayland after building v2.2.1 from source.

**Comment by jdnixx** [comment] 2024-02-06 14:34
Doesn't show anything on my machine (when I click the icon on the taskbar, I see it fly away to the upper-left corner of the screen as if it's opening a window, but it's tiny and no window actually appears). What even is this window? Also it appears espanso suddenly isn't expanding anything at all for me today but probably a separate issue

![image](https://github.com/espanso/espanso/assets/24235975/475f20d8-965b-4c5b-8281-945ac6eaaf6e)

**Comment by readtedium** [comment] 2024-02-06 14:45
One interesting thing about the window, at least for me, is that when you press the escape key, something happens within it. It appears to be an open dialog box that is 1 pixel wide.

**Comment by morgan-dgk** [comment] 2024-02-06 15:02
@jdnixx this window is used to sync keyboard modifier between evdev and xkb under wayland (see #972). #1769 updated the client library used to create this window (smithay-client-toolkit, sctk) to resolve a crash on start-up under wayland. Unfortunately, this window no longer closes as expected once the sync is completed and the associated event loop exits. 

I have been digging into this for awhile and have reached out to the maintainers of sctk to request assistance. However, I am at a bit of a dead-end currently. I tried updating sctk to v18 (the latest version) and updating the code in evdev/sync/wayland to match the new sctk API, but the issue persists.

Would welcome any assistance :slightly_smiling_face:

**Comment by AucaCoyan** [comment] 2024-02-12 19:08
I'm looking to `git bisect` the problem, but I can't currently run espanso in my debian virtual machine 😢 .
I'll try to fix first [this issue](https://github.com/espanso/espanso/issues/1793) that is stopping me here to use espanso in debian 12
```
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by AucaCoyan** [comment] 2024-02-13 03:20
Hi! I could solve the problem 😄 , it's not merged yet, but I would like you all to clone this PR #1849 and try it. 
This should solve the problem. If you see any problem, please ring me! I'm not sure if I will break something by leaving `$auto` in the dpkg dependencies.

**Comment by readtedium** [comment] 2024-02-13 04:09
Hi, did this with manual compilation in Nobara Linux (Fedora derivative) and can confirm it no longer shows the odd window.

Thanks @AucaCoyan for the work to resolve this.

**Comment by bentolor** [comment] 2024-02-13 13:21
Thanks @AucaCoyan for your efforts to resolve this issues. I just tried to do the requested under **Ubuntu 22.04.3 LTS** and on first glance your work actually seems to resolve the issue! 🎉 

* I had to use/install an older `libwxgtk` library: `sudo apt install libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev libwxgtk3.0-gtk3-dev`
* After building & installing the created `.deb`, the service is was no longer starting up. I had forgotten that I needed to re-execute `sudo setcap "cap_dac_override+p" $(which espanso)` to fix permission issues.


Right now it seems to be working. Thanks for your great guide how to build locally!

**Comment by AucaCoyan** [comment] 2024-02-13 13:47
Thanks to you both for testing! It gives me a hug in my coder heart to achieve success ❤️

**Comment by AucaCoyan** [comment] 2024-03-14 15:48
Hello! #1901 got merged, can we re-test if this keeps happening in the latest version? ❤️

**Comment by bentolor** [comment] 2024-03-14 16:03
I just built `dev` (https://github.com/espanso/espanso/commit/4e6839c4fa4bb1325d38a5b434dcbc4a61289533) and installed it. 
It seems the issue is no longer happening in `dev` trunk for me.

Thank you, @AucaCoyan!

**Comment by AucaCoyan** [comment] 2024-03-14 17:01
All kudos to @morgan-dgk !

**Comment by distefam** [comment] 2024-03-14 19:04
Thanks @morgan-dgk! I can confirm this fixes it for me on Fedora 39 with Gnome (Wayland).

**Closed as completed** 2024-03-14 19:09 UTC
Labels: bug, Linux, wayland

**Comment by tomstafford** [comment] 2024-11-06 08:58
Successful today, on Ubuntu 24.04 with Wayland. @bentolor's [comment](https://github.com/espanso/espanso/issues/1826#issuecomment-1941505085) helped, but libwxgtk3.0-gtk3-dev has been deprecated so I used 

`sudo apt install libwxgtk3.2-dev `

then compiled from source following [https://espanso.org/docs/install/linux/#wayland-compile](https://espanso.org/docs/install/linux/#wayland-compile)


And it worked

**Comment by joebordes** [comment] 2024-11-06 09:02
can we get a new release distributed through normal update channels?

**Comment by AucaCoyan** [comment] 2024-11-06 11:56
Sadly no, because of #2126

**Comment by theoden-dd** [comment] 2024-11-20 09:20
Succeeded today on Ubuntu 22.04 with Wayland.
Simply followed the instructions in: https://espanso.org/docs/install/linux/#wayland-compile

The window has disappeared, the input focus's stopped from constant switching off on keyboard layout switching.

Thank you guys for the great project and documentation!
Good luck on the keys issues/releases! <3
