### ISSUE TITLE
After migration, the useful commented docs have been removed from the files

### ISSUE THREAD

**Issue by MikhailTNY** [federico-terzi/espanso#874] opened 2021-11-14 15:33 UTC
After migrating with 2.1.0-alpha, the useful commented docs were replaced with just this: 

```
# Automatically generated by espanso migration tool
# Original file: default.yml
```

It would be nice to include the updated specs below that, so I can see the new formats and how they're laid out as well as the defaults + available options in the config file.

**Comment by federico-terzi** [comment] 2021-11-15 18:50
Hey @MikhailTNY,

Thank you for the feedback!

> the useful commented docs have been removed from the files

Unfortunately, there is not much we can do about it at the moment... The migration parses the files, converts them to the new format and then output the updated YAML files. The problem is that comments are lost in the parsing phase, and we don't have any YAML parser in Rust that preserve comments

> It would be nice to include the updated specs below that, so I can see the new formats and how they're laid out as well as the defaults + available options in the config file.

Good point, I've originally decided against it because I didn't want to fill the config files with comments (which might be confusing). We'll think about that :)

I'll close the issue for now, as we don't have any feasible way to implement it at the moment. I'll make sure to reopen if the situation changes

Cheers :)

**Closed by federico-terzi** 2021-11-15 18:50 UTC

**Comment by MikhailTNY** [comment] 2021-11-15 18:55
One of the reasons for including the docs is that if we use text editors like Visual Studio Code, we can auto-complete settings based on the file content. So, if the config file had 

> Shortcuts available:  `LEFT_SHIFT, RIGHT_SHIFT`, etc. 

I can type `LE` and it'll let me autocomplete. This avoids any errors from sneaking in when saving the file.

**Comment by federico-terzi** [comment] 2021-11-15 19:19
@MikhailTNY That's a good point, I hope the new upcoming editor will solve this problem as well :)

**Comment by MikhailTNY** [comment] 2021-11-15 19:39
I can't wait. BTW, awesome job on this update!
