### ISSUE TITLE
Keys typed on the keyboard's numpad don't trigger replacement

### ISSUE THREAD

**Issue by lual** [federico-terzi/espanso#406] opened 2020-08-17 13:19 UTC
For a spreadsheet, I just tried to simplify the time-format typing by replace `,,` by the `:`
Because I've to type a lot of fields and I try to avoid the colon-sign, (which makes me slow)

This will do the job:
```
  - trigger: ",,00"
    replace: ":00"
  - trigger: ",,01"
    replace: ":01"
  - trigger: ",,02"
    replace: ":02"
...
  - trigger: ",,59"
    replace: ":59"
```

This works unless i use the keys on the keyboard's numpad. :(

(on Linux)

**Comment by federico-terzi** [comment] 2020-08-18 14:03
Hey,
I'm sorry you experienced this problem, which distro are you using?
Cheers :)

**Comment by lual** [comment] 2020-08-18 14:13
...Linux Mint 19.3 Cinnamon
I tried to implement the same task with Autokey. -> Same problem there. 
So maybe it's not an espanso problem.  
It's only a minor issue for me. 
I just wanted to let you know.
You may close this case.
Thanks for your work.

**Comment by federico-terzi** [comment] 2020-08-18 14:19
Thank you. Just a thought, are you sure numlock is enabled?

**Comment by lual** [comment] 2020-08-18 14:24
Yes, of course ;)
I can type on the numpad, but the replacement will not occur like on the main part of the keyboard.

**Comment by federico-terzi** [comment] 2020-08-19 15:19
@lual All right, thank you. I'll investigate :)

**Comment by federico-terzi** [comment] 2020-09-16 19:22
Hey @lual,
I've looked into this issue and the strange thing is, it's working for me! What keyboard layout do you use?
Cheers :)

**Comment by lual** [comment] 2020-09-17 07:04
...German (DE) standard layout. 
But i tweaked my Linux Mint to get rid of the CAPSLOCK key - that way:
"Systemeinstellungen > Tastatur > Tastaturbelegungen > Optionen > Verhalten der Feststelltaste > ist deaktiviert"
translated maybe...
"Settings > Keyboard > Mapping > Options > Behavior of Capslock > deactivated"

Also I've installed Autokey in parallel.

And maybe there are more specials on my PC.

If this issue is only affecting me - then please close it!
Thanks a lot for investigate.
(And for espanso generally)

**Comment by federico-terzi** [comment] 2020-09-18 16:51
Great, thank you :)
I'm going to close the issue as I cannot reproduce. If someone else is affected, please reopen the issue 👍

**Closed** 2020-09-18 16:51 UTC
Labels: Linux, bug
