### ISSUE TITLE
Incorrect replacements with pressed Shift key

### ISSUE THREAD

**Issue by formicant** [federico-terzi/espanso#1944] opened 2024-04-13 07:09 UTC
### Description

Now, replacements do not occur while a shift key is pressed. Instead, they are activated after the shift key is released, This can lead to incorrect replacements.

### Steps to reproduce

1. Add the following match:
  ``` yaml
  matches:
    - trigger: ":)"
      replace: "☺"
  ```
2. Hold a shift key down
3. Type `:)TEXT` (without releasing the shift key)
4. Release the shift key

The actual result is:
`:)TE☺`

### Expected behavior

`☺TEXT`

### Your environment

- Environment name and version: rust 1.75.0 (82e1608df 2023-12-21)
- Operating system: Arch Linux, X11, KDE Plasma 6.0.3
- Espanso version 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment] 2024-04-13 15:00
Duplicate of #940, #1405.

**Closed as completed by smeech** 2024-04-13 15:00 UTC
Labels: bug
