### ISSUE TITLE
Fails to install external package from `main` branch (expects `master` branch)

### ISSUE THREAD

**Issue by lukeburns** [federico-terzi/espanso#684] opened 2021-06-01 00:16 UTC
Github changed the default branch from `master` to `main` (https://github.com/github/renaming), and espanso tries to extract packages from the `master` branch.

Example: 
```
> espanso install julia-completions https://github.com/lukeburns/julia-completions --external
Allowing external repositories
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Invalid zip header")', src/package/zip.rs:62:56
```
because the file `https://github.com/lukeburns/julia-completions/archive/refs/heads/master.zip` does not exist.

**Comment by lukeburns** [comment] 2021-06-01 00:18
Good first issue for someone learning rust!

**Comment by federico-terzi** [comment] 2021-06-01 17:33
Hey @lukeburns,

Thanks for reporting this issue! Looks like this is a duplicate of #526, so I'm closing it in favor of that one :)

Cheers :)

**Closed by federico-terzi** 2021-06-01 17:33 UTC
