### ISSUE TITLE
Espanso (Portable) Search Bar - Incorrect Display on Multi-Monitor Setup

### ISSUE THREAD

**Issue by rashabarbar** [federico-terzi/espanso#1910] opened 2024-03-22 05:09 UTC
**Describe the bug**
In a dual-monitor setup, Espanso (Portable) search bar opens (very small) on the primary display when invoked using the shortcut (Alt+Spacebar) in any application on the secondary monitor.

**Expected behavior**
Search bar should appear on the display with the focused application (secondary monitor)

**Logs**
22:05:48 [worker(7004)] [WARN] rendering was aborted by extension: choice, on var: output

**Setup information**
- OS: Windows 10
- Version: Portable app v 2.1.8

**Comment by smeech** [comment] 2024-03-23 10:07
Duplicate of #983, #782, #779.

**Closed as completed** 2024-03-23 10:07 UTC
Labels: bug
