### ISSUE TITLE
Shell command execution is broken

### ISSUE THREAD

**Issue by graphixillusion** [federico-terzi/espanso#269] opened 2020-05-10 11:49 UTC
Hi there. The execution of a shell command using espanso seems to be broken under Windows 10. Using the default.yml file, with the default setting:

```
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
```
 when you type **":shell"** this error will appear:

**"Hello" is not recognized as an internal or external command, operable program or batch file.**

**Comment by federico-terzi** [comment] 2020-05-10 11:57
Hey,
Thanks for the report. I tried to reproduce the problem but I'm unable to do so, as the example you proposed works correctly for me on Windows.
Are you trying to use it in a terminal?

**Comment by graphixillusion** [comment] 2020-05-10 12:06
Thanks to you for the support. Yes, i'm using the standard "cmd" terminal. I just tried with "powershell" too and this is the result:

PS C:\Users\User> Hello from your shell
Hello : The term 'Hello' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
In line:1 car:1
+ Hello from your shell
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Hello:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

As you can see from the log, the echo command appears in the powershell terminal followed by this error.

**Comment by federico-terzi** [comment] 2020-05-10 12:15
All right, probably a little bit of clarification will make things more clear:
The shell extension is not used to type things in the terminal, but rather to execute the command you specify and then insert the output of this command as an extension.
You don't need to use a shell extension to type things in the terminal, just use a normal match:

```yaml
- trigger: ":hello"
  replace: "Hello from your shell"
```

Your example return an error, because what happens is that espanso executes "echo Hello from your shell", which produces "Hello from your shell" as an output (with a newline at the end, which simulates an enter command).
As a result, the current terminal you are in will try to interpret "Hello from your shell" as a command, which of course is not valid.

I'm not sure if it is clear at this point, could you please explain what are you trying to accomplish?

**Comment by graphixillusion** [comment] 2020-05-10 12:22
Yes, i understand the differences. I was trying to execute a very long command like:

**scoop update && scoop update * && scoop cleanup * && scoop cache rm ***

but doesn't work, that's why i tried the default config and realize that it doesn't work either.

**Comment by federico-terzi** [comment] 2020-05-10 12:36
Glad you sorted that out :) Let me know if you have other doubts, I'm going to close the issue for now

**Closed by federico-terzi** 2020-05-10 12:36 UTC
Labels: Windows, bug

**Comment by graphixillusion** [comment] 2020-05-10 12:41
Only the standard replacement works. This config doesn't:

- trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "scoop update && scoop update * && scoop cleanup * && scoop cache rm *"

**Comment by federico-terzi** [comment] 2020-05-10 16:59
Hey,
I'm not sure I understood correctly. Do you want espanso to execute `scoop update && scoop update * && scoop cleanup * && scoop cache rm *` or to just paste it in the terminal?

Cheers

**Comment by graphixillusion** [comment] 2020-05-10 18:33
@federico-terzi yes, espanso should paste in the terminal that command, then execute it.

**Comment by federico-terzi** [comment] 2020-05-10 18:38
All right, now I understand what you are trying to do. Could you please try using this match:

```yaml
- trigger: ":shell"
  replace: "scoop update && scoop update * && scoop cleanup * && scoop cache rm *\n"
```

**Comment by graphixillusion** [comment] 2020-05-10 18:44
@federico-terzi yep, exactly like this. Works perfectly! Thank you!

**Comment by federico-terzi** [comment] 2020-05-11 07:10
You're welcome :)
