### ISSUE TITLE
Windows 10 build 2004. Just doesn't work.

### ISSUE THREAD

**Issue by nunya77** [federico-terzi/espanso#477] opened 2020-10-01 14:18 UTC
Installed latest version (.72)  on Windows 10 build 2004 in virtualbox 6.1. System install went ok. First run caused BSOD. System rebooted before I could get dump location.
Not able to find a dump. Espanso shows installed, and process runs. But nothing happens, and the status icon doesnt' show up.

espanso status will sometimes state not running when there are copies of espanso.exe listed in taskmanager.
sometimes it just comes back with a blank line.
:espanso test is what caused first BSOD. No response from espanso since. (Although system pauses a moment like it's trying to do something when typing the expand codes.
Have since removed espanso since it has caused the vm I'm running it in to randomly "abort".

**Comment by nunya77** [comment] 2020-10-01 15:27
Ok. Don't know why, but Webroot DNS Protector was causing an issue. I have removed webroot dns protector, and now espanso works. Care to comment on why espanso needs internet to work? And what's it connecting to that is so bad that webroot needs to block it?

**Comment by federico-terzi** [comment] 2020-10-01 16:51
Hi @nunya77,

I'm sorry you experienced this problem! I've never used Webroot DNS Protector, is it an anti-virus? Espanso is known to trigger false alarms with anti-viruses (as the binary itself is not signed).

> Care to comment on why espanso needs internet to work?

Espanso only accesses the internet when installing a package (typing `espanso install <package>` in the terminal), so that's definitely strange. I'll investigate.

Cheers

**Comment by federico-terzi** [comment] 2020-10-01 17:21
@nunya77 I've also tried running espanso version 0.7.2 (from the installer found online) in a clean VM with Wireshark open and I couldn't see any network traffic...
Any chance you could give me a bit more information to reproduce?

**Comment by nunya77** [comment] 2020-10-02 16:22
Well, I added an md5 exception for the espanso.exe (But to get that I had to remove webroot, which was a pain)...the md5 includes the %appdata%\programs\     path.  However, now when espanso pastes, it jumbles things up and duplicates some letters, removes all trailing whitespace prior to the paste,  (Webroot DNS Protector is part of the corporate webroot package which blocks access to sites known to have infected items. I also am not able to see the traffic, but by putting the md5 exception in, espanso is now loading, don't know what to do about installing, aside from doing an md5 of the installer and adding that to the whitelist as well.)  If I don't have webroot, espanso works perfectly. (However, I don't know that it's webroot, as in order to remove webroot I also had to remove LogMeIN, and other MNS related software, which was just put back on together in one installer.)
Here is the output of the default test for espano:Hih it hte:espanso  
(I typed that four lines down with garbage text in between since I knew it would delete some things.)

(I really want this to work, as so far every Text expander I have tried has issues, including Phrase Express, and Text Expander).
Both phrase express and text expander break pasting altogether and cause Unicode pastes which changes everything to random Chinese characters. 
I take it espanso is actually sending things one keystroke at a time, and webroot must be trying to scan the contents which is causing things to get messed up in the process.

**Comment by federico-terzi** [comment] 2020-10-03 07:50
Hey,

> as so far every Text expander I have tried has issues, including Phrase Express, and Text Expander

Then, unfortunately, espanso is unlikely to work as all text expanders use the same mechanisms of expansion...

> I take it espanso is actually sending things one keystroke at a time, and webroot must be trying to scan the contents which is causing things to get messed up in the process.

That's very likely, but unfortunately, I don't see any solution... The problem is outside the reach of espanso itself (and probably most text expanders out there).

I'm closing the issue as it doesn't seem related to espanso itself, but rather about your current system. I only have a limited amount of time and unfortunately, I can't dedicate much time to this issue.

I hope you will understand, let me know if you have any other concern

**Closed by federico-terzi** 2020-10-03 07:50 UTC
Labels: Windows, bug, investigate

**Comment by nunya77** [comment] 2020-10-05 15:33
Have a case open w/ Webroot. The issues are different for each. So I doubt that webroot is the cause. Phrase Express, and Text Expander both have those issues with and without antivirus. (Just windows 10 related issues to windows turning Uni-Code pasting back on just because foreign language support is enabled. This is not a unicode issue.  But if webroot comes up w/ a solution, that is implemented outside of webroot, (or even inside of it.) I'll post results here, as google is already pulling this up.

**Comment by nunya77** [comment] 2020-10-05 19:35
Alright discovered issue. (Did not realize espanzo was installed in my host environment, as I don't recall putting it there (Linux Mint).
so 2 copies were catching the input. WIndows copy in Virtualbox, and Linux copy. Removed linux copy, as I don't have a need for it at this time. However, when it was just the linux copy running, espanso (with a colon in front) expanded to Hi there1 instead of Hi there! (So will check the YML file later from linux to see if it's in error there.

**Comment by federico-terzi** [comment] 2020-10-06 11:00
@nunya77 Thanks for your investigation, that happened to me as well many months ago when using a virtual machine... Took me a while to figure out :)
