### ISSUE TITLE
espanso for ipad to share shortcuts?

### ISSUE THREAD

**Issue by ReblochonMasque** [federico-terzi/espanso#908] opened 2021-12-13 02:26 UTC
Hello Federico, thanks for espanso, it is a wonderful app.

Are there plans to extend the range to include ipad for sharing shortcuts?

**Comment by federico-terzi** [comment] 2021-12-13 22:02
Hey @ReblochonMasque,

Thank you for the kind words! iOS support is by far the hardest to accomplish due to the many technical limitations, but I'm definitely not against it. There are a lot of higher priority things to do first, but perhaps in the future, we might work on the iOS port as well :)

This is a duplicate of https://github.com/federico-terzi/espanso/issues/610, I'm closing this one in favor of the other one. Feel free to continue the discussion there :)

Cheers :)

**Closed by federico-terzi** 2021-12-13 22:02 UTC

**Comment by ReblochonMasque** [comment] 2021-12-14 00:04
noted, thanks.
