### ISSUE TITLE
espanso match list --json returns wrong replace

### ISSUE THREAD

**Issue by kud** [federico-terzi/espanso#2013] opened 2024-07-11 10:44 UTC
```
  {
    "triggers": [
      "??r.okletsgo"
    ],
    "replace": "Ok Let's Go",
    "label": "Ok Let's Go"
  },
```

here, `replace` is equivalent to `label`. It should not be when you see the source:

```
  - trigger: "??r.okletsgo"
    label: "Ok Let's Go"
    replace: "https://www.youtube.com/watch?v=AWM5ZNdWlqw"
```

**Comment by smeech** [comment] 2024-07-11 10:49
Duplicate of #1702

**Closed as not planned by smeech** 2024-07-11 10:49 UTC
Labels: bug
