### ISSUE TITLE
done all the steps and espanso is running but no expansion

### ISSUE THREAD

**Issue by maxandersen** [federico-terzi/espanso#197] opened 2020-03-09 22:48 UTC
macOS Catalina
version 10.15.3
installed via brew tap federico-terzi/espanso
enabled in accessibiilty.

textexpand and typinator works - but not espansa also tried running without anything else running. no expansion.

**Comment by federico-terzi** [comment] 2020-03-10 09:13
Hey @maxandersen,
I'm sorry you experienced these issues! Could you please post the output of the `espanso log` command here?

Could you also please try to double tap the Option key (ALT) and see if that enables espanso? 

Cheers :)

**Comment by federico-terzi** [comment] 2020-05-05 16:52
Hey,
I'm going to close the issue as it seems like the problem is no longer relevant.
Let me know if you have other doubts :)

**Closed by federico-terzi** 2020-05-05 16:52 UTC
Labels: MacOS, bug, investigate

**Comment by maxandersen** [comment] 2020-05-05 22:26
sorry - missed your comment.

I *think* it might just be me double tapping alt twice but not sure...can I change it to be triple tap or turn it of completely ? :)

**Comment by federico-terzi** [comment] 2020-05-06 11:09
Espanso doesn't support triple taps, but you can disable it completely by adding:

```yaml
toggle_key: OFF
```

to your `default.yml` file :)
