### ISSUE TITLE
Clipboard data truncated to 2047 characters if trigger initiated with data in clipboard over 2047 characters

### ISSUE THREAD

**Issue by KyleSnodgrass** [federico-terzi/espanso#1841] opened 2024-02-07 21:28 UTC
**Describe the bug**
clipboard characters are "clipped" to 2047 if more than 2048 characters are copied to the clipboard and a trigger is then implemented.

**To Reproduce**
#### Initial Testing
- Copy info to the clipboard, in this case 4199 characters.
Pasting:
```
~/Downloads > espanso log                                                                                                                                                                                16:05:31
16:01:04 [daemon(27896)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [daemon(27896)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [daemon(27896)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [daemon(27896)] [INFO] watching for changes in path: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] espanso version: 2.2.1
16:01:04 [daemon(27896)] [INFO] spawning the worker process...
16:01:04 [daemon(27896)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansodaemonv2.sock
16:01:04 [worker(27897)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [worker(27897)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [worker(27897)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [worker(27897)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [worker(27897)] [INFO] using CocoaAppInfoProvider
16:01:04 [worker(27897)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansoworkerv2.sock
16:01:04 [worker(27897)] [INFO] monitoring the status of the daemon process
16:01:04 [worker(27897)] [INFO] monitoring the status of secure input
16:01:04 [worker(27897)] [INFO] using CocoaSource
16:01:04 [worker(27897)] [INFO] using MacInjector
16:01:04 [worker(27897)] [INFO] using CocoaClipboard
16:02:23 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:02:25 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
~/Downloads > espanso log                                                                                                                                                                                16:05:36
16:01:04 [daemon(27896)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [daemon(27896)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [daemon(27896)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [daemon(27896)] [INFO] watching for changes in path: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] espanso version: 2.2.1
16:01:04 [daemon(27896)] [INFO] spawning the worker process...
16:01:04 [daemon(27896)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansodaemonv2.sock
16:01:04 [worker(27897)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [worker(27897)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [worker(27897)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [worker(27897)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [worker(27897)] [INFO] using CocoaAppInfoProvider
16:01:04 [worker(27897)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansoworkerv2.sock
16:01:04 [worker(27897)] [INFO] monitoring the status of the daemon process
16:01:04 [worker(27897)] [INFO] monitoring the status of secure input
16:01:04 [worker(27897)] [INFO] using CocoaSource
16:01:04 [worker(27897)] [INFO] using MacInjector
16:01:04 [worker(27897)] [INFO] using CocoaClipboard
16:02:23 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:02:25 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
```
- Trigger my "date1" trigger:
    - 02/07/2024
- Paste the same clipboard:
```
~/Downloads > espanso log                                                                                                                                                                                16:05:31
16:01:04 [daemon(27896)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [daemon(27896)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [daemon(27896)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [daemon(27896)] [INFO] watching for changes in path: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] espanso version: 2.2.1
16:01:04 [daemon(27896)] [INFO] spawning the worker process...
16:01:04 [daemon(27896)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansodaemonv2.sock
16:01:04 [worker(27897)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [worker(27897)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [worker(27897)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [worker(27897)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [worker(27897)] [INFO] using CocoaAppInfoProvider
16:01:04 [worker(27897)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansoworkerv2.sock
16:01:04 [worker(27897)] [INFO] monitoring the status of the daemon process
16:01:04 [worker(27897)] [INFO] monitoring the status of secure input
16:01:04 [worker(27897)] [INFO] using CocoaSource
16:01:04 [worker(27897)] [INFO] using MacInjector
16:01:04 [worker(27897)] [INFO] using CocoaClipboard
16:02:23 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:02:25 [worker(27897)] [WARN] detected inconsistent modifier state f
```
- reduced to 2047 characters. 
    - perhaps espanso is setting the clipboard size? 
#### Further Testing
- copy the clipped clipboard, after adding `aaaaaaa` to the end to increase the number of characters copied over 2048:
~/Downloads > espanso log                                                                                                                                                                                16:05:31
16:01:04 [daemon(27896)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [daemon(27896)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [daemon(27896)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [daemon(27896)] [INFO] watching for changes in path: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] espanso version: 2.2.1
16:01:04 [daemon(27896)] [INFO] spawning the worker process...
16:01:04 [daemon(27896)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansodaemonv2.sock
16:01:04 [worker(27897)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [worker(27897)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [worker(27897)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [worker(27897)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [worker(27897)] [INFO] using CocoaAppInfoProvider
16:01:04 [worker(27897)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansoworkerv2.sock
16:01:04 [worker(27897)] [INFO] monitoring the status of the daemon process
16:01:04 [worker(27897)] [INFO] monitoring the status of secure input
16:01:04 [worker(27897)] [INFO] using CocoaSource
16:01:04 [worker(27897)] [INFO] using MacInjector
16:01:04 [worker(27897)] [INFO] using CocoaClipboard
16:02:23 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:02:25 [worker(27897)] [WARN] detected inconsistent modifier state faaaaaaa

- Issued my trigger to set the markdown for a block quote, pasted the data inbetween the markdown block quote ticks:
```
~/Downloads > espanso log                                                                                                                                                                                16:05:31
16:01:04 [daemon(27896)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [daemon(27896)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [daemon(27896)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [daemon(27896)] [INFO] watching for changes in path: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] espanso version: 2.2.1
16:01:04 [daemon(27896)] [INFO] spawning the worker process...
16:01:04 [daemon(27896)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansodaemonv2.sock
16:01:04 [worker(27897)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [worker(27897)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [worker(27897)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [worker(27897)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [worker(27897)] [INFO] using CocoaAppInfoProvider
16:01:04 [worker(27897)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansoworkerv2.sock
16:01:04 [worker(27897)] [INFO] monitoring the status of the daemon process
16:01:04 [worker(27897)] [INFO] monitoring the status of secure input
16:01:04 [worker(27897)] [INFO] using CocoaSource
16:01:04 [worker(27897)] [INFO] using MacInjector
16:01:04 [worker(27897)] [INFO] using CocoaClipboard
16:02:23 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:02:25 [worker(27897)] [WARN] detected inconsistent modifier state f
```
- data clipped to 2047 characters again.
**Expected behavior**
If copying 4199 characters running a trigger and then pasting afterward I would expect the same clipboard contents to come out. 

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem
```
~/Downloads > espanso log                                                                                                                                                                                16:20:51
16:01:04 [daemon(27896)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [daemon(27896)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [daemon(27896)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [daemon(27896)] [INFO] watching for changes in path: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [daemon(27896)] [INFO] espanso version: 2.2.1
16:01:04 [daemon(27896)] [INFO] spawning the worker process...
16:01:04 [daemon(27896)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansodaemonv2.sock
16:01:04 [worker(27897)] [INFO] reading configs from: "/Users/kyle/Library/Preferences/espanso"
16:01:04 [worker(27897)] [INFO] reading packages from: "/Users/kyle/Library/Application Support/espanso/packages"
16:01:04 [worker(27897)] [INFO] using runtime dir: "/Users/kyle/Library/Application Support/espanso"
16:01:04 [worker(27897)] [INFO] system info: Darwin v14.3 - kernel: 23.3.0
16:01:04 [worker(27897)] [INFO] using CocoaAppInfoProvider
16:01:04 [worker(27897)] [INFO] binded to IPC unix socket: /Users/kyle/Library/Application Support/espanso/espansoworkerv2.sock
16:01:04 [worker(27897)] [INFO] monitoring the status of the daemon process
16:01:04 [worker(27897)] [INFO] monitoring the status of secure input
16:01:04 [worker(27897)] [INFO] using CocoaSource
16:01:04 [worker(27897)] [INFO] using MacInjector
16:01:04 [worker(27897)] [INFO] using CocoaClipboard
16:02:23 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:02:25 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:09:26 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:12:04 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:20:28 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
16:20:30 [worker(27897)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
```
**Setup information**
- OS: 14.3 this issue was present in all versions of Mac and espanso I've used. I've been an espanso users for about 2.5 years. I started on 0.7.3 I think.
- Version: which version of Espanso are you running? just upgraded to 2.2.1 from 2.1.8

**Comment by smeech** [comment] 2024-02-11 15:19
Just to clarify, are you talking about a return of clipboard contents via Espanso, such as in:
```
  - trigger: :test
    replace: "{{output}}"
    vars:
      - name: output
        type: clipboard
```
?
As it works fine here (Linux Mint Xfce), tested to over 20k characters before I gave up! I presume it's _not_ hard-coded in Espanso. Perhaps it's a macOS issue?
```
  - trigger: :test
    replace: |
      **************************************************
```
etc., with many repeats of the last line works too.

**Comment by KyleSnodgrass** [comment] 2024-02-11 23:44
Hey @smeech,
   Good question. I'm referencing the OS clipboard. However, I just tested on another Mac, I have a fresh install of espanso (2.2.1 with the default library, so no other .yml files to look through other than base.yml) and I was unable to replicate the behavior. The other device I run espanso on has several hundred yml files with many many triggers... perhaps that has something to do with it. 
   
   The Mac I just tested on: 12.7.2 Perhaps it is an OS version issue. I'll try and migrate my other espanso library to this Mac and see if I get the same results. 
   
   Thanks for looking at this and replying.

**Comment by smeech** [comment] 2024-02-11 23:58
Would you be happy to close this Issue?

**Comment by KyleSnodgrass** [comment] 2024-02-12 00:03
I'm not trying to leave open items for you guys.. however, it does seem that espanso is involved. Are you indicating that I should test on the other espanso setup and if I have more detail open another issue? Or are you indicating that this shouldn't have been filed as a bug? I've been dealing with this issue for several years, so I wasn't sure if there was some way that espanso was inelegantly interacting with the OS clipboard. If you don't think that's the case then we can close this. If you'd like me to provide more information I can also do that.

**Comment by smeech** [comment] 2024-02-12 12:20
That's absolutely fine, I'm happy to leave it open. I'm afraid I've got the end of my macOS expertise (basically none, although I'm aware it has similarities with Linux). It's been very useful to know that it's not occurring in all installations.
We could do with more input from macOS users - are you on the [Discord](https://discord.gg/4QARseMS6k) server? - there are several there who might be willing to check it out, and it's probably most useful if you do it directly.
Otherwise, we'll see if someone else notices it here, and chips in.

**Comment by kpym** [comment] 2024-02-17 18:05
This seems to be a duplicate of #1612.

**Comment by smeech** [comment] 2024-02-17 18:34
Thank you. I'll close this in favour of the older issue, which brings in Windows, and has a longer and slightly more fruitful discussion.

**Closed as not planned by smeech** 2024-02-17 18:34 UTC
Labels: MacOS

**Comment by KyleSnodgrass** [comment] 2024-02-18 19:04
Thanks for looking into this, team. I did wonder if I was covering some of the same issues as in 1612, but I noted an important distinction between this issue and 1612. The OS clipboard is affected by any trigger in this issue. In 1612, it seems the Clipboard feature needs to be specified. Am I misunderstanding?

**Comment by kpym** [comment] 2024-02-18 19:26
@KyleSnodgrass You are absolutely correct. And I can confirm that this is also the case on Windows. 

I don't know what's best: having two related issues or a single one.

**Comment by smeech** [comment] 2024-02-18 19:42
Thank you. They're linked now anyway.
I've confirmed it's not an issue on Linux (here, at least) and added the appropriate tags to #1612.

**Comment by dmwyatt** [comment] 2024-03-24 19:06
I'm getting slightly lower than 2047 characters, though it doesn't seem to be consistent.  The last two tries I've gotten 1977 and 2000 characters.  This happens whether or not I'm using a `clipboard` var.  Any time espanso is triggered, text in my clipboard gets truncated.

On Windows 11.

**Comment by smeech** [comment] 2024-03-24 19:33
Is `xclip` any better?

**Comment by kpym** [comment] 2024-03-24 22:09
> I'm getting slightly lower than 2047 characters, though it doesn't seem to be consistent. The last two tries I've gotten 1977 and 2000 characters. 

IMO the espanso limit is 2048 bytes, which could represent less characters if some of them use more than one byte (non-ASCII characters in UTF8 for example).

**Comment by dmwyatt** [comment] 2024-03-24 22:14
> Is `xclip` any better?

If you're talking to me, I'm not sure what you mean since `xclip` isn't a Windows thing, AFAIK.

> IMO the espanso limit is 2048 bytes, which could represent less characters if some of them use more than one byte (non-ASCII characters in UTF8 for example).

I think this is probably it.
