### ISSUE TITLE
Espanso not running in background on linux

### ISSUE THREAD

**Issue by AleandroPagani** [federico-terzi/espanso#2159] opened 2024-11-29 11:24 UTC
### Description

I'm on arch linux with gnome 47.2 / wayland.
I installed the wayland version of espanso and the app is working but i always have a "window" open and its icon on the app launcher (look at the image) so it's not really running in background as i think it should.

Is it a bug or the expected behavior? There is a workaround eventually?
Thanks in advance.

### Screenshots

![Issue](https://github.com/user-attachments/assets/518f2489-f6b6-4fea-98d0-0716421c36e5)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment] 2024-11-29 14:49
Duplicate of :
#2156
#1776
#1722
#1619

Fixed in the current `dev` code, but you'd need to compile, until we can find a way to make the next release (certificate issues).

**Closed as completed by smeech** 2024-11-29 14:49 UTC
Labels: bug, needs-triage
