### ISSUE TITLE
Autoreload not working for Espanso v2 on Linux

### ISSUE THREAD

**Issue by xircon** [federico-terzi/espanso#769] opened 2021-10-09 08:41 UTC
Installed:
```
 aur/espanso-git r1058.8f291f4-1 [installed] [2+] [0.00%] [6 Oct 2021]
```
Currently running KDE 

Previously espanso reload the config on the fly when edits were saved,  it is not doing this,  I have to stop/start for it to recognize alterations.

Also the `espanso restart` command has completely disappeared?  This was really useful.

**Comment by federico-terzi** [comment] 2021-10-09 16:32
> Previously espanso reload the config on the fly when edits were saved, it is not doing this, I have to stop/start for it to recognize alterations.

@xircon Sorry I forgot, could you please post the output of `espanso log` here? Auto reload should be already working, so this is likely a bug :)

**Comment by federico-terzi** [comment] 2021-10-09 17:27
> No, normal files btrfs file system

@xircon I see, thank you. We'll investigate :)

> Where did espanso migrate store the backup? I have a backup, but cannot find the migrate "backup" 😄

It should be located in the Documents folder :)

**Comment by Scrumplex** [comment] 2021-10-09 17:40
> @Scrumplex Didn't notice you already updated the AUR packages for the new version! Thank you for that :)
> Given these problems, would it be possible to rollback to the legacy version for now (hosted on the [legacy](https://github.com/federico-terzi/espanso/tree/legacy) branch) and create another AUR package for the v2?
> I expect the new version to be fully usable in about a month, so we should point to the old version for now. What do you think? :)

I only updated espanso-git for now. AFAIK Arch Linux guidelines say, that -git should be preferred if the user wants to try beta versions. So for now it should be fine for users to use -git for the new stuff (makes bug reporting easier as well). I am sure I can release a espanso-legacy package once 2.X.X is stable.

**Comment by federico-terzi** [comment] 2021-10-09 17:49
@xircon I see what you mean, thank you. We'll work on it 👍  https://github.com/federico-terzi/espanso/issues/772

> Also, the migrate did not cope with this:
> 
> ```
>   - trigger: "eskel"
>     replace: "  - trigger:\n$|$  replace:"
> ```

This one is very interesting. The migration tool converts it to:

```yaml
  - trigger: eskel
    replace: |-
        - trigger:
      $|$  replace:
```

which would be valid YAML, but because of the two starting spaces, it messes up the indentation and the YAML file becomes invalid. This looks like a bug of the [yaml-rust](https://github.com/chyh1990/yaml-rust) library we are using. I've opened an issue: https://github.com/federico-terzi/espanso/issues/771

> I only updated espanso-git for now. AFAIK Arch Linux guidelines say, that -git should be preferred if the user wants to try beta versions. So for now it should be fine for users to use -git for the new stuff (makes bug reporting easier as well). I am sure I can release a espanso-legacy package once 2.X.X is stable.

@Scrumplex All right, sounds good! Thank you for the help :)

**Comment by xircon** [comment] 2021-10-10 15:08
Not that I am aware of, the 0.7.3 version works fine:
![image](https://user-images.githubusercontent.com/1316691/136701700-f8041997-2999-48d6-8e3b-7e57d1d75a01.png)

**Comment by federico-terzi** [comment] 2021-10-10 16:35
@xircon That's a really good point! If version 0.7.3 is working, then it should be something else :) I'll try editing the file with Emacs to see if it might be related

**Comment by federico-terzi** [comment] 2021-10-10 19:48
@xircon Thank you for the detailed report! I was finally able to reproduce it consistently.

For example, inside vim the reload works if I only save with ":w", but doesn't work if I save and quit with ":wq".
It probably has to do with the temporary files that get created, I'll investigate :)

**Comment by federico-terzi** [comment] 2021-10-10 20:39
All right, I fixed the wrong debouncing algorithm that was causing this problem. Thank you again for the help in diagnosing the issue!

I'll probably release version `v2.0.2-alpha` later tomorrow, which ships with a fix for this problem and the  one related to the invalid migration :)

**Closed as completed** 2021-10-11 19:01 UTC
Labels: bug, Linux
