### ISSUE TITLE
Arch wayland weird visual bug on boot

### ISSUE THREAD

**Issue by BramSuurdje** [federico-terzi/espanso#1843] opened 2024-02-08 10:49 UTC
**Describe the bug**
Every time i start my arch instance. i get the a weird full screen RGB window from espanso and i can't close it. 

**To Reproduce**
- Install arch with hyprland
- install espanso for wayland
- start it
1.

**Expected behavior**
For espanso to start on the background with no popups (because it is allready a systemctl service)

**Screenshots**
![Screenshot_08-Feb_11-40-27_2565](https://github.com/espanso/espanso/assets/78373894/66d8d539-b587-4147-a41d-c249fbe8709c)

**Logs**
```
11:46:23 [daemon(7722)] [INFO] reading configs from: "/home/bram/.config/espanso"
11:46:23 [daemon(7722)] [INFO] reading packages from: "/home/bram/.config/espanso/match/packages"
11:46:23 [daemon(7722)] [INFO] using runtime dir: "/home/bram/.cache/espanso"
11:46:23 [daemon(7722)] [INFO] system info: Arch Linux v - kernel: 6.7.4-arch1-1
11:46:23 [daemon(7722)] [WARN] keyboard layout watcher couldn't determine active layout.
11:46:23 [daemon(7722)] [INFO] espanso version: 2.2.1
11:46:23 [daemon(7722)] [INFO] spawning the worker process...
11:46:23 [daemon(7722)] [INFO] watching for changes in path: "/home/bram/.config/espanso"
11:46:23 [daemon(7722)] [INFO] binded to IPC unix socket: /home/bram/.cache/espanso/espansodaemonv2.sock
11:46:23 [worker(7728)] [INFO] reading configs from: "/home/bram/.config/espanso"
11:46:23 [worker(7728)] [INFO] reading packages from: "/home/bram/.config/espanso/match/packages"
11:46:23 [worker(7728)] [INFO] using runtime dir: "/home/bram/.cache/espanso"
11:46:23 [worker(7728)] [INFO] system info: Arch Linux v - kernel: 6.7.4-arch1-1
11:46:23 [worker(7728)] [INFO] binded to IPC unix socket: /home/bram/.cache/espanso/espansoworkerv2.sock
11:46:23 [worker(7728)] [INFO] using WaylandAppInfoProvider
11:46:23 [worker(7728)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
11:46:23 [worker(7728)] [INFO] monitoring the status of the daemon process
11:46:23 [worker(7728)] [INFO] using EVDEVSource
11:46:24 [worker(7728)] [INFO] Querying modifier status...
11:46:24 [worker(7728)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
11:46:24 [worker(7728)] [INFO] using EVDEVInjector
11:46:24 [worker(7728)] [INFO] using WaylandFallbackClipboard
11:47:59 [daemon(7722)] [INFO] configuration change detected, restarting worker process...
11:47:59 [worker(7728)] [INFO] engine eventloop has terminated, propagating exit event...
11:47:59 [worker(7728)] [INFO] waiting for engine exit mode...
11:47:59 [worker(7728)] [INFO] exiting worker process...
11:47:59 [daemon(7722)] [INFO] spawning the worker process...
11:47:59 [worker(9123)] [INFO] reading configs from: "/home/bram/.config/espanso"
11:47:59 [worker(9123)] [INFO] reading packages from: "/home/bram/.config/espanso/match/packages"
11:47:59 [worker(9123)] [INFO] using runtime dir: "/home/bram/.cache/espanso"
11:47:59 [worker(9123)] [INFO] system info: Arch Linux v - kernel: 6.7.4-arch1-1
11:47:59 [worker(9123)] [INFO] binded to IPC unix socket: /home/bram/.cache/espanso/espansoworkerv2.sock
11:47:59 [worker(9123)] [INFO] using WaylandAppInfoProvider
11:47:59 [worker(9123)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
11:47:59 [worker(9123)] [INFO] monitoring the status of the daemon process
11:47:59 [worker(9123)] [INFO] using EVDEVSource
11:48:00 [worker(9123)] [INFO] Querying modifier status...
11:48:00 [worker(9123)] [INFO] inject module will use this keyboard layout: [R=, M=, L=us, V=, O=]
11:48:00 [worker(9123)] [INFO] using EVDEVInjector
11:48:00 [worker(9123)] [INFO] using WaylandFallbackClipboard
```

**Setup information**
- OS: Arch linux
- Version: 2.2.1

**Comment by morgan-dgk** [comment] 2024-02-08 14:27
@smeech please close as duplicate of #1776 and #1722.

**Comment by smeech** [comment] 2024-02-08 14:36
I agree - duplicate.

**Closed as completed** 2024-02-08 14:37 UTC
Labels: bug, wayland
