### ISSUE TITLE
Espanso Freezes the entire desktop when expanding a match

### ISSUE THREAD

**Issue by Luctins** [federico-terzi/espanso#237] opened 2020-04-14 16:25 UTC
Every time espanso finds a matching expansion I cannot interact with the desktop for 5-10 seconds, but the mouse cursor still moves.
Most of the time this happens the trigger text is not completely erased. 
Espanso's own logs and `journalctl` were of not much use debugging this.
Tried using clipboard, auto and inject for the backend; same result.

Info:
pt-br keyboard layout
```
sb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

gnome-shell --version
GNOME Shell 3.28.4

echo $XDG_SESSION_TYPE 
x11

```

`espanso dump`
[config.txt](https://github.com/federico-terzi/espanso/files/4476495/config.txt)

**Comment by federico-terzi** [comment] 2020-04-14 16:29
Hey @Luctins,

That is pretty strange indeed, thanks for pointing it out! Some questions for you:

* How many matches/packages have you installed?
* Could you please try the following procedure and see if that helps?
Switch to a US keyboard layout, restart espanso, type any match.

Let me know if you experience problems in that case as well.

Cheers :)

**Comment by Luctins** [comment] 2020-04-14 16:30
examples:
On gedit:
![espanso-bug](https://user-images.githubusercontent.com/4743486/79249514-bdcdfc00-7e53-11ea-991b-afbbc303e910.gif)
on firefox:
![espanso-bug2 gif](https://user-images.githubusercontent.com/4743486/79249657-fb328980-7e53-11ea-880c-fcbf2e66c748.gif)

**Comment by Luctins** [comment] 2020-04-14 16:31
I use:
```
espanso package list
basic-emojis - 0.1.0
shruggie - 0.1.0
```

**Comment by Luctins** [comment] 2020-04-14 16:33
Uninstalled all packages and tested again, same result

**Comment by Luctins** [comment] 2020-04-14 16:57
tested with US keyboard: could not interact with the desktop, and the "shell error tone" was played in quick sucession, could not recover desktop.

**Comment by federico-terzi** [comment] 2020-04-14 17:05
> tested with US keyboard: could not interact with the desktop, and the "shell error tone" was played in quick sucession, could not recover desktop.

That is very strange @Luctins, I'm sorry you experienced these issues. Are you using a stock Ubuntu installation?

**Comment by Luctins** [comment] 2020-04-14 17:29
thanks for taking the time to help :smile:.
The only major modification that I recall was uninstalling the nouveau driver (It's a hybrid graphics laptop).

**Comment by federico-terzi** [comment] 2020-04-14 18:57
All right, thank you. I'll try to reproduce this myself and get back to you if I find something :)

**Comment by federico-terzi** [comment] 2020-04-16 16:59
Hey @Luctins,

I was able to reproduce the issue, and after a lot of digging it seems to be a problem related to Gnome with some keyboard layouts, including the pt-br that you are using. (See [https://bugs.launchpad.net/ubuntu/+source/meta-gnome3/+bug/1777708](https://bugs.launchpad.net/ubuntu/+source/meta-gnome3/+bug/1777708))

In the above post, it explains a workaround:

With admin rights, edit the `/usr/share/X11/xkb/symbols/br` and comment out this line:
```
modifier_map Mod3 { Scroll_Lock };
```
so that it becomes:

```
//modifier_map Mod3 { Scroll_Lock };
```

Then reboot the system. Espanso should be a lot more responsive by then.

Let me know if that helps!

Cheers :)

**Comment by Luctins** [comment] 2020-04-17 17:04
Wow, that's a not very obvious issue to track down.
As you have suggested I do have 2 keyboards (It's a laptop with a USB keyboard plugged in).
Applied the suggested modification and it seems to do it, Thanks :smile:. 

as a bonus, probably will make my desktop more stable overall (I was having mini freezes from time to time for a while now).
Close the issue?

**Comment by federico-terzi** [comment] 2020-04-17 17:11
You're welcome :)
I'm going to close the issue now, let me know if you have other doubts

Cheers

**Closed by federico-terzi** 2020-04-17 17:11 UTC
Labels: Linux, bug

**Comment by xnhp** [comment] 2021-07-13 10:54
Hi, 

I am having a similar issue. However, I am on windows and use the default (german) keyboard layout.

After entering a trigger pattern, all inputs arrive extremely slowly and the trigger pattern is removed and the replacement inserted sluggishly over the next ~6 seconds.

I did not make any real customisations; this is my config:

```
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Change the key used to toggle espanso active mode
toggle_key: "OFF"

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ".ra"
    replace: "→"

  - trigger: ".dra"
    replace: "⇒"

  - trigger: ".cf"
    replace: "↝"

  - trigger: ".--"
    replace: "—"

  - trigger: ";b"
    replace: " •"

  - trigger: ".phi"
    replace: "ϕ"

  - trigger: ".ck"
    replace: "✓"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd:  "echo Hello from your shell"
```

**Comment by federico-terzi** [comment] 2021-07-13 16:51
Hey @xnhp,

I'm sorry you experienced this problem! Does it happen on every application? This sounds strange because espanso is usually pretty snappy on Windows

Cheers :)

**Comment by xnhp** [comment] 2021-07-14 13:51
Heyo, thanks for the quick reply.

The issue seems unrelated to Espanso. I could observe the same issue in some specific cases of autocompletion by PyCharm. Or maybe anytime if a sequence of characters is entered in quick succession.

In any case, a reboot seems to have fixed it for now. I'll report back if this ever becomes relevant again.

Thanks anyway.

**Comment by federico-terzi** [comment] 2021-07-16 17:22
Sounds good! Thank you for the follow up :)

**Comment by Arcstur** [comment] 2021-09-15 16:36
Hello, I'm having the same issue. Replacement takes longer than 2 seconds. I also use pt-br layout, but it happens in the same way with the en layout. I tried commenting out in the "br" file as above, it made it a little bit faster, but still is taking around 2 seconds.

The thing is, this is happening on Zorin Os 16, but is NOT happening in Boddhi Linux 6. 

In Boddhi Linux, the replacements are made in a fraction of a second, every single one.

In Zorin, the replacements with no "special characters" are made in a fraction of a second, but the replacements which contain letters with diacritcs, like ê (which is in my name), á, é, or an emoji 🌎 , are freezing the desktop.

**Comment by Arcstur** [comment] 2021-09-15 18:09
I tried with Zorin Os Lite, which uses XFCE, and it doesn't freeze. So it should be something with GNOME indeed.

**Comment by federico-terzi** [comment] 2021-09-15 18:37
@Arcstur Interesting! Thank you for reporting

Given that the upcoming v2 (#594) comes with a brand new engine, we might want to wait for it to see if the problem persists, and then tackle the problem again if so :)

**Comment by federico-terzi** [comment] 2021-10-05 06:12
@xnhp That's interesting, thanks for sharing!
