### ISSUE TITLE
Multiline trigger? Making a match that only applies on new line

### ISSUE THREAD

**Issue by bennotkin** [federico-terzi/espanso#518] opened 2020-11-18 15:51 UTC
First of all, thank you for this wonderful tool that's become key to my daily work. Every day I find a new application for it, and I'm telling everyone to use espanso. 

Is it possible to include a line break in the _trigger_?

I'm led to believe it is because in #124 you wrote "for now, you could get it working by using \n inside the trigger". I can't get this to work, though, and (given the context of #124) wonder if you were simply referring to putting \n in the replacement.

Makes sense if it's not possible, but because of your comment I thought I'd check.

My real goal is to have a match that only happens when I start a new line

      - trigger: "\ntrig"
        replace: "\nrep"

I've tried a few iterations and none work. Also tried typing in literal `\n` to see if the trigger was taking it literally, but found it wasn't.

Again, probably not a very important use case, but thought I'd seek clarity.

Thanks!

**Comment by federico-terzi** [comment] 2020-11-20 19:48
Hey @bennotkin,

Thanks for the kind words! This seems to be a duplicate of #205, so I'm going to close it in favor of that one :)
Unfortunately, it's difficult to predict when this feature will become available, but I'm planning an architectural rewrite in the next few months, so I'll make sure to consider this feature as well!

Cheers :)

**Closed by federico-terzi** 2020-11-20 19:48 UTC
