### ISSUE TITLE
Case insensivity for triggers

### ISSUE THREAD

**Issue by ivan-paleo** [federico-terzi/espanso#824] opened 2021-10-27 10:53 UTC
Is there a way to make the triggers case-insensitive? 
For example with:
```
- trigger: "hello"
  replace: "world"
```
If you type "Hello", this won't replace it with "world". I'd like that "hello", "Hello", "hEllo" etc. all trigger the replacement. With a few letters already, using multiple triggers get quickly unmanageable.
Case propagation could be used with that simple example, but this is not ideal for other cases where e.g. capitalization of the replacement is fixed (like in German).

**Comment by federico-terzi** [comment] 2021-12-29 19:57
Just noticed this is a duplicate of https://github.com/federico-terzi/espanso/issues/824, feel free to continue the discussion there :)

**Closed by federico-terzi** 2021-12-29 19:57 UTC
Labels: Feature

**Comment by ivan-paleo** [comment] 2022-01-03 08:40
Well, this issue _**is**_ #824! So either you referenced the wrong issue above, or there is no duplicate...?

**Comment by federico-terzi** [comment] 2022-01-06 18:37
@ivan-paleo You're absolutely right! I'm sorry about that. I wanted to write this message in #905, but wrote it here by mistake. Feel free to continue the discussion there :)

**Comment by smeech** [comment] 2024-03-09 13:12
Associated discussion #1245

**Comment by KeronCyst** [comment] 2025-03-14 01:56
This issue should be reopened, no? SikuliX users could really benefit from any sort of `ignore_case: true`, which has outrageously specific, counterintuitive capitalization, such as:

```
click(Location(X,Y))
rightClick(Location((X,Y))
doubleClick(Location(X,Y))
keyDown(KEY_CTRL)
```

If you mess up _any_ of this capitalization, it won't work.

**Comment by smeech** [comment] 2025-03-14 09:13
> This issue should be reopened, no? SikuliX users could really benefit from any sort of `ignore_case: true`, which has outrageously specific, counterintuitive capitalization, such as:
> 
> ```
> click(Location(X,Y))
> rightClick(Location((X,Y))
> doubleClick(Location(X,Y))
> keyDown(KEY_CTRL)
> ```
> 
> If you mess up _any_ of this capitalization, it won't work.

The examples above suggest you're referring to the case of the _replacements_? They should work reliably in simple triggers.

For the case of the triggers themselves we now have the options to use `triggers:` or `regex:` inputs.

I'm probably misunderstanding your comment, I'm afraid!
