### ISSUE TITLE
Expanding with wrong keyboard layout when fast_inject is activated

### ISSUE THREAD

**Issue by westerlind** [federico-terzi/espanso#260] opened 2020-05-02 22:45 UTC
The new fast_inject feature for Linux can lead to expanding with the wrong keyboard layout.

I'm using Swedish keyboard layout, but when using Espanso on Fedora (Gnome) it tries to expand with English keyboard layout instead, which means that some characters gets wrong (all - turns into + and @ turns into " for example).

It is like it's trying to press the key that would have been correct if my keyboard layout was English, but instead gets whatever is in that same position on the keyboard with Swedish keyboard layout.

I haven't figured out what the difference is, but in Manjaro (Gnome) with seemingly the same keyboard configuration, this is not happening, and everything works perfectly.

**Comment by federico-terzi** [comment] 2020-05-03 12:23
Hey @westerlind,

Thank you for reporting this issue! I honestly don't really know what could be causing it, as espanso uses a slightly modified version of libxdo which handles the keyboard injection mechanism.

I'll take a look in the next days and get back to you if I find a solution. 

In the mean time, you could try disabling the `fast_inject` option altogether on Fedora. Is is slow without it? As some systems (Gnome in particular) seem to suffer when not using fast_inject.

Cheers :)

**Comment by westerlind** [comment] 2020-05-05 19:47
Hi

It does actually work well enough for me to still love using it even without fast_inject, but it is very nice to have this extreme speed that fast_inject introduces :)

Anyway, this problem seems to have gone away by itself. So it's a good thing that I'm not having the issue anymore, but less of a good thing that I didn't manage to figure out what caused it before it disappeared, so it might come back again.

Could it be a possibility that this might have to do with me running espanso as a snap? I could imagine that the snap environment could treat things like which keyboard layout I'm using slightly differently, and then possibly cause an issue like this, but I don't know the snap system good enough to be able to say if that's actually possible.
If the problem comes back, I will try to see if there is a difference if I run it "directly", and not as a snap.

**Comment by federico-terzi** [comment] 2020-05-06 11:46
Hey,
Nice to hear that, although this behavior is pretty strange.
Let me know if the problem comes back again and if you figured out the steps to reproduce it :)

**Comment by jcassee** [comment] 2020-06-01 20:50
I seem to have run into the same problem. (Please correct me if it is a different one.)

I'm using Dvorak, and today espanso was outputting gibberish, recognizable from when I am typing blind on a querty keyboard. :slightly_smiling_face: Even when I selected querty layout, the output was the same. When I restarted espanso, the output was back to normal.

Anything I can do to help debug the problem if it occurs again?

**Comment by federico-terzi** [comment] 2020-06-02 07:43
Hey @jcassee,
Thank you for reporting this problem. The best thing to help me would be some steps to reproduce the issue, even though they might be difficult to get :)

If the problem is very rare, I'd say restarting espanso could be a decent workaround in the meanwhile.

**Comment by federico-terzi** [comment] 2020-09-03 20:03
Hey,
I'm closing this issue as I wasn't able to find a way to reproduce the problem. If anyone has an idea on how to reproduce it reliably, please reopen the issue.

Cheers :)

**Closed by federico-terzi** 2020-09-03 20:03 UTC
Labels: Linux, bug

**Comment by Facyla** [comment] 2020-09-07 08:20
Hello, 
Not sure how reproductible it is, however i'm having consistently the same issue on Ubuntu 18.04 / Gnome, french layout keyboard. 
I'd suspect some tool uses a different keyboard layout config than the one used by the loggedin in user ?  Maybe something to snap ?

**Comment by Facyla** [comment] 2020-09-07 08:21
Espanso was firstly installed with snap. I installed the .deb version, restarted the daemon, and the issue has disappeared.

**Comment by federico-terzi** [comment] 2020-09-07 21:10
@Facyla this is interesting, I'll investigate. Might be the same problem as #447

**Comment by jcassee** [comment] 2020-09-20 18:53
> @Facyla this is interesting, I'll investigate. Might be the same problem as #447

I can confirm that my version of this problem matches #447 exactly.
