### ISSUE TITLE
Add support for Kinto on Windows - Espanso stops working after installing Kinto, showing the clipboard manager when trying to paste snippets/replacements.

### ISSUE THREAD

**Issue by bigplayer-ai** [federico-terzi/espanso#2061] opened 2024-09-16 16:00 UTC
### Description

After installing [Kinto ](https://github.com/rbreaves/kinto)on Windows 11 23H2, Espanso no longer pastes snippets and only displays clipboard manager. This issue is similar to what happens with other text replacement tools like Beeftext.

[Kinto ](https://github.com/rbreaves/kinto)interferes with text replacement tools such as Espanso and Beeftext, preventing snippets from being pasted and showing the clipboard manager instead.

### Motivation

Espanso should be compatible with [Kinto ](https://github.com/rbreaves/kinto)to ensure snippets paste correctly without interference. This would greatly improve the user experience for those using both tools.

### Alternatives

None of the alternatives (other snippet tools or manual AHK tweaks) have worked.

Here is the bug documented:
![kinto-espanso-bug](https://github.com/user-attachments/assets/70eb91bc-f949-4c02-9931-f5af1c4c637d)

I don't know on which side the issue can be fixed and I really don't expect either of you to fix it, but perhaps one of you can look into it.

[kinto issue](https://github.com/rbreaves/kinto/issues/876) :[https://github.com/rbreaves/kinto/issues/876](https://github.com/rbreaves/kinto/issues/876)
[espanso issue](https://github.com/espanso/espanso/issues/2061): [https://github.com/espanso/espanso/issues/2061](https://github.com/espanso/espanso/issues/2061)
Thanks

I noticed that espanso/beeftext gets the text correctly to the clipboard, but they fails to paste it/replace the text after putting it in to the clipboard...
![kinto-clipboard-bug-ezgif com-optimize](https://github.com/user-attachments/assets/0a3dd6d8-c107-4b50-83a4-3e982c1b8f25)

once I change the clipboard backend to inject, I got this error:
```
19:56:50 [daemon(35228)] [INFO] reading configs from: "[CONFIG_PATH]"
19:56:50 [daemon(35228)] [INFO] reading packages from: "[PACKAGE_PATH]"
19:56:50 [daemon(35228)] [INFO] using runtime dir: "[RUNTIME_DIR]"
19:56:50 [daemon(35228)] [INFO] system info: Windows v11 (22631) - kernel: 22631
19:56:50 [daemon(35228)] [INFO] watching for changes in path: "[CONFIG_PATH]"
19:56:50 [daemon(35228)] [INFO] espanso version: 2.2.1
19:56:50 [daemon(35228)] [INFO] spawning the worker process...
19:56:50 [daemon(35228)] [INFO] binded to named pipe: "\\.\pipe\espansodaemonv2"
19:56:50 [worker(1748)] [INFO] reading configs from: "[CONFIG_PATH]"
19:56:50 [worker(1748)] [INFO] reading packages from: "[PACKAGE_PATH]"
19:56:50 [worker(1748)] [INFO] using runtime dir: "[RUNTIME_DIR]"
19:56:50 [worker(1748)] [INFO] system info: Windows v11 (22631) - kernel: 22631
19:56:50 [worker(1748)] [INFO] binded to named pipe: "\\.\pipe\espansoworkerv2"
19:56:50 [worker(1748)] [INFO] using Win32AppInfoProvider
19:56:50 [worker(1748)] [INFO] monitoring the status of the daemon process
19:56:50 [worker(1748)] [INFO] using Win32Source
19:56:50 [worker(1748)] [INFO] using Win32Injector
19:56:50 [worker(1748)] [INFO] using Win32Clipboard
19:56:57 [worker(1748)] [WARN] extension 'clipboard' on var: 'clipb' reported an error: clipboard provider returned error
19:56:57 [worker(1748)] [ERROR] error during rendering: rendering error

Caused by:
    clipboard provider returned error
```

I noticed that clipboard manager does not work at all with kinto, which is more serious (not related to espanso or any other text replacements/snippets softwares) I mean the native Windows clipboard manager, once using kinto it stops pasting anything when selecting anything from windows native clipboard manager.

Kinto URL: https://github.com/rbreaves/kinto
### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment] 2024-10-05 11:45
Whilst I agree it would be nice to resolve this, it appears the problem is with Kinto, as other text expanders behave similarly.
I'll close this as duplicate.

**Closed as completed by smeech** 2024-10-05 11:45 UTC

**Comment by bigplayer-ai** [comment] 2024-10-05 13:26
> Whilst I agree it would be nice to resolve this, it appears the problem is with Kinto, as other text expanders behave similarly. I'll close this as duplicate.

I found a solution by changing the Paste key to Alt + V in Espanso’s config files. While it still behaves oddly, especially during remote connections, this adjustment resolved the issue on my local machine that runs Kinto.

**Comment by smeech** [comment] 2024-10-05 13:33
Good - you might find an app-specific configuration helps avoid it deleteriously affecting function in other programs.
