### ISSUE TITLE
Add config to context menu

### ISSUE THREAD

**Issue by pedzed** [federico-terzi/espanso#887] opened 2021-11-26 19:43 UTC
### Problem Description
On Mac, the config is located at `$HOME/Library/Preferences/espanso/default.yml`, on Linux it is located at `$HOME/.config/espanso/default.yml` and on Windows it is located at `%APPDATA%\espanso\default.yml`. Whether one uses multiple operating systems or not, it would be nice to be able to quickly find the config.

For the CLI, one can use `espanso config`, but nothing is available for the GUI.

### Proposal
After "Reload config" in the context menu, I propose to add "Open config".

![Espanso context menu](https://user-images.githubusercontent.com/8146593/143624281-ec4341fd-9c9a-4253-876f-ae576959dbc0.png)

### Discussion
An important thing to note is that every operating system provides a different file explorer (Finder on Mac, Explorer on Windows, Nautilus on Ubuntu, etc.). How can we take care of those differences, if we were to open the config directory?

Even more important to note if we were to open with a text editor, in what editing program should it be opened with? Ideally, Espanso would come with a GUI to edit the config, but that would be for another issue (perhaps one is already created?).

### Related Code
https://github.com/federico-terzi/espanso/blob/aa9465490b141d8816f49d10328aa3836cfe3902/espanso-engine/src/process/middleware/context_menu.rs#L81-L84

**Comment by pedzed** [comment] 2021-11-26 19:45
Apparently a similar issue for this already exists: #449. Sorry about that.

**Comment by federico-terzi** [comment] 2021-11-27 10:29
Hey @pedzed,

Thank you for the feedback! I agree this feature would be useful, and I'm looking forward to implementing it in the near future :)
Given that this is a duplicate of #449, I'm closing this one in favor of the other one. Feel free to continue the discussion there :)

Cheers :)

**Closed by federico-terzi** 2021-11-27 10:29 UTC
