### ISSUE TITLE
Custom path for location of default.yml

### ISSUE THREAD

**Issue by bazmcbrien** [federico-terzi/espanso#572] opened 2021-01-26 12:33 UTC
Hey @federico-terzi 
Just donated $5. Couldn't spare more unfortunately. Your app is fantastic!!!
So I've Mac and Linux laptops and soon to have a Windows one. A feature I would love to see in the future would be the ability to be able to to change the location of where the default.yml is saved. I use NextCloud between both laptops for sharing files and if I could change the location to a folder in there I wouldn't have to copy over the default.yml to the other machine each time I edit. 
Hope I'm making sense.
Best
appManDo

**Comment by federico-terzi** [comment] 2021-01-26 13:30
Hey @bazmcbrien,

Thanks for the generosity and the feedback! This is a duplicate of #267 so I'm going to close this issue in favor of the other one. Feel free to continue the discussion there

In the meanwhile, you could follow the steps described in the [Sync](https://espanso.org/docs/sync/) section of the docs to directly synchronize the configs using NextCloud

Cheers :)

**Closed by federico-terzi** 2021-01-26 13:30 UTC

**Comment by bazmcbrien** [comment] 2021-01-26 13:39
Cool!!!
