### ISSUE TITLE
Windows (11) : Alt code doesn't work

### ISSUE THREAD

**Issue by Mara-Li** [federico-terzi/espanso#1060] opened 2022-04-04 13:25 UTC
**Describe the bug**
Alt code is unusable when espanso run. The state of the app (enabled/disabled) doesn't change anything; to type alt code i need to quit completely the app. 

What I try : 
- Toggle off `toggle_key` ; `search_shortcut` and `search_trigger`
- Clean and reinstall espanso from repo
- Reinstall with administrator
- Trying restart with sudo (gsudo package on windows)
- Clean / removing all previous configuration

**To Reproduce**
1. Start espanso
2. Try to type any key for keyboard, for example ALT+255 (invisible space) or alt+7 

**Expected behavior**
The alt code work and the special character appear. 

**Screenshots**
/

**Logs**
15:11:06 [daemon(6500)] [INFO] reading configs from: "C:\\Users\\etulyon1\\AppData\\Roaming\\espanso"
15:11:06 [daemon(6500)] [INFO] reading packages from: "C:\\Users\\etulyon1\\AppData\\Roaming\\espanso\\match\\packages"
15:11:06 [daemon(6500)] [INFO] using runtime dir: "C:\\Users\\etulyon1\\AppData\\Local\\espanso"
15:11:06 [daemon(6500)] [INFO] watching for changes in path: "C:\\Users\\etulyon1\\AppData\\Roaming\\espanso"
15:11:06 [daemon(6500)] [INFO] espanso version: 2.1.5-beta
15:11:06 [daemon(6500)] [INFO] spawning the worker process...
15:11:07 [daemon(6500)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
15:11:07 [worker(10168)] [INFO] reading configs from: "C:\\Users\\etulyon1\\AppData\\Roaming\\espanso"
15:11:07 [worker(10168)] [INFO] reading packages from: "C:\\Users\\etulyon1\\AppData\\Roaming\\espanso\\match\\packages"
15:11:07 [worker(10168)] [INFO] using runtime dir: "C:\\Users\\etulyon1\\AppData\\Local\\espanso"
15:11:07 [worker(10168)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
15:11:07 [worker(10168)] [INFO] using Win32AppInfoProvider
15:11:07 [worker(10168)] [INFO] monitoring the status of the daemon process
15:11:07 [worker(10168)] [INFO] using Win32Source
15:11:07 [worker(10168)] [INFO] using Win32Injector
15:11:07 [worker(10168)] [INFO] using Win32Clipboard
15:11:08 [worker(10168)] [WARN] unable to find espanso AppUserModelID in the list of registered ones, falling back to Powershell

**Setup information**
- OS: Windows 11
- Version: espanso 2.1.5-beta

**Comment by federico-terzi** [comment] 2022-04-05 19:37
Hey @Mara-Li,

Thanks for reporting this issue! This is a duplicate of https://github.com/federico-terzi/espanso/issues/988, I'm closing this one in favor of the other one. Feel free to continue the discussion there :)

Cheers :)

**Closed by federico-terzi** 2022-04-05 19:37 UTC
Labels: bug
