### ISSUE TITLE
Replacement isn't triggered until SHIFT key is released

### ISSUE THREAD

**Issue by garlicbreadcleric** [federico-terzi/espanso#2045] opened 2024-09-01 17:39 UTC
### Description

I'm trying to do replacements from `->` to `→`. The problem is, typing `>` requires holding `SHIFT`, so usually the space after `>` is typed while `SHIFT` is not released, and espanso doesn't do replacement until shift is released, and replaces wrong part of the text. I tried all of the injection backends (`auto`, `clipboard`, `inject`) — they all behave the same in this instance. None of the other config settings are changed from the default.

### Steps to reproduce

Config:
```yaml
matches:
  - trigger: "->"
    replace: "\u2192"
```

1. Typing `-[SHIFT DOWN]>[SHIFT UP]` results in `→` — as expected.
2. Typing `-[SHIFT DOWN]> [SHIFT UP]` results in `-→` — it replaced `> ` instead of `->`.
3. Typing `-[SHIFT DOWN]>ABC[SHIFT UP]` results in `->A→` and so on.

### Expected behavior

Replacement should be done regardless of whether `SHIFT` is released or not. If that's not possible due to some technical limitation, the matched part should be replaced correctly.

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0): Rust 1.80.0
- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Kubuntu 24.04 (X11)
- Espanso version (e.g., 2.1.4-beta): fd9a7dd4f2afccaeb61623286b1230c0df0c7033 — latest dev (built from source); also observed on b421bcf73fa13506938d62425459d6c16c6a8d0a — latest master (2.2.1, built from source as well)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment] 2024-09-01 22:51
Duplicate of #940, #1405, #1944, & possibly #399.

**Closed as completed by smeech** 2024-09-01 22:51 UTC
Labels: bug
