### ISSUE TITLE
Multiline strings

### ISSUE THREAD

**Issue by Tzahreddin** [federico-terzi/espanso#124] opened 2019-11-21 17:44 UTC
Hi, I used espanso for the first time and was not able to create a multiline replacement.

I used https://yaml-multiline.info/ as model, but nothing worked with espanso.

Am I using it wrong or is that 'feature' / yaml-Syntax not implemented?

Best

**Comment by federico-terzi** [comment] 2019-11-22 08:07
Hi @Tzahreddin,
Thanks for the feedback. I've experienced that problem too, I think it's due to the way `serde` implements it's parser. For now, you could get it working by using `\n` inside the trigger.
I'll take a look at the bug whenever possible and let you know.

Thanks for your help

**Comment by federico-terzi** [comment] 2019-11-28 18:36
Hi @Tzahreddin,
I've looked into your issue and multiline strings are working correctly for me on MacOS. Which operating system are you using?
Try with this syntax:
```yaml
  - trigger: ":test"
    replace: |
      test
      multiline
```

Let me know if it works in your machine so that we can close this issue.

Thanks for your help

**Comment by federico-terzi** [comment] 2019-12-13 19:54
Considering that there have been no updates on this issue, I'll close it now as I can't reproduce the problem.
Let me know if you need more help.

Cheers

**Closed by federico-terzi** 2019-12-13 19:54 UTC
Labels: bug
