### ISSUE TITLE
Trigger on Return

### ISSUE THREAD

**Issue by malwikl** [federico-terzi/espanso#902] opened 2021-12-08 08:54 UTC
**Is your feature request related to a problem? Please describe.**
It should be possible to trigger only when the return/enter key is pressed

**Describe the solution you'd like**
define a trigger like "XYZ\n"
where "\n" is just a placeholder to indicate that the return key is part of the trigger

**Comment by federico-terzi** [comment] 2021-12-08 11:44
Hey @malwikl,

Thank you for the feedback! This is a duplicate of https://github.com/federico-terzi/espanso/issues/205, I'm closing this one in favor of the other one. Feel free to continue the discussion there :)

Cheers :)

**Closed by federico-terzi** 2021-12-08 11:44 UTC
