### ISSUE TITLE
PopOS! 22.04 Won't install deb

### ISSUE THREAD

**Issue by dodalovic** [federico-terzi/espanso#1090] opened 2022-04-27 14:44 UTC
```shell
➜  Downloads sudo apt install ./espanso-debian-x11-amd64.deb

[sudo] password for dod:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'espanso' instead of './espanso-debian-x11-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 espanso : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by jdnixx** [comment] 2022-04-27 17:26
Was just about to post this issue. Same on Kubuntu 22.04. Apparently dotnet has the same type of issue, it's because ubuntu jammy only packages libssl3
https://github.com/dotnet/sdk/issues/24759

**Comment by federico-terzi** [comment] 2022-05-01 18:34
I'm sorry you experienced this problem! This is a duplicate of #1056, closing in favor of that one

**Closed by federico-terzi** 2022-05-01 18:34 UTC
Labels: bug
