### ISSUE TITLE
I have a permanent opened app on fedora 39 

### ISSUE THREAD

**Issue by rysete** [federico-terzi/espanso#1794] opened 2023-12-18 00:44 UTC
**Describe the bug**
I'm using gnome 45 on fedora 39 and the lasted version of espanso, with wayland.
Following the official site instalation process and setting as a service,the result, an unknown program eternally running in my notebook, seeing on sys monitor was 3 espanso "apps" running.
**To Reproduce**
1. Install fedora 39, updated, dash to dock and some other extensions. like Forge for tilling
2. Follow espanso instalation process
3. Denided that to run as a service 

**Expected behavior**
I believe it would work as a service and not as a program, with icontray maybe or nothing.
**Screenshots**
![Captura de tela de 2023-12-17 21-30-14](https://github.com/espanso/espanso/assets/56932297/d9290f46-9059-409b-bfc3-9a60fee02be0)
![Captura de tela de 2023-12-17 21-30-27](https://github.com/espanso/espanso/assets/56932297/cfb410be-f21a-40c6-a321-e8cd2bf60b30)

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

espanso log
11:32:41 [daemon(3060)] [INFO] reading configs from: "/home/ryse/.config/espanso"
11:32:41 [daemon(3060)] [INFO] reading packages from: "/home/ryse/.config/espanso/match/packages"
11:32:41 [daemon(3060)] [INFO] using runtime dir: "/home/ryse/.cache/espanso"
11:32:41 [daemon(3060)] [INFO] system info: Fedora Linux v39 - kernel: 6.6.6-200.fc39.x86_64
11:32:41 [daemon(3060)] [INFO] watching for changes in path: "/home/ryse/.config/espanso"
11:32:41 [daemon(3060)] [INFO] espanso version: 2.2.0
11:32:41 [daemon(3060)] [INFO] spawning the worker process...
11:32:41 [daemon(3060)] [INFO] binded to IPC unix socket: /home/ryse/.cache/espanso/espansodaemonv2.sock
11:32:41 [daemon(3060)] [WARN] keyboard layout watcher couldn't determine active layout.
11:32:41 [worker(3067)] [INFO] reading configs from: "/home/ryse/.config/espanso"
11:32:41 [worker(3067)] [INFO] reading packages from: "/home/ryse/.config/espanso/match/packages"
11:32:41 [worker(3067)] [INFO] using runtime dir: "/home/ryse/.cache/espanso"
11:32:41 [worker(3067)] [INFO] system info: Fedora Linux v39 - kernel: 6.6.6-200.fc39.x86_64
11:32:41 [worker(3067)] [INFO] binded to IPC unix socket: /home/ryse/.cache/espanso/espansoworkerv2.sock
11:32:41 [worker(3067)] [INFO] using WaylandAppInfoProvider
11:32:41 [worker(3067)] [INFO] monitoring the status of the daemon process
11:32:41 [worker(3067)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
11:32:41 [worker(3067)] [INFO] using EVDEVSource
11:32:41 [worker(3067)] [INFO] Querying modifier status...
11:32:55 [worker(3067)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
11:32:55 [worker(3067)] [INFO] using EVDEVInjector
11:32:55 [worker(3067)] [INFO] using WaylandFallbackClipboard
11:52:04 [worker(3067)] [WARN] Can't read from device /dev/input/event20, this error usually means the device has been disconnected, removing from epoll.
11:52:04 [worker(3067)] [WARN] Can't read from device /dev/input/event16, this error usually means the device has been disconnected, removing from epoll.
21:21:43 [service(65486)] [INFO] reading configs from: "/home/ryse/.config/espanso"
21:21:43 [service(65486)] [INFO] reading packages from: "/home/ryse/.config/espanso/match/packages"
21:21:43 [service(65486)] [INFO] using runtime dir: "/home/ryse/.cache/espanso"
21:21:43 [service(65486)] [INFO] system info: Fedora Linux v39 - kernel: 6.6.6-200.fc39.x86_64
21:21:43 [service(65486)] [WARN] service file already exists, this operation will overwrite it
21:21:43 [service(65486)] [INFO] creating service file in "/home/ryse/.config/systemd/user/espanso.service"
21:21:43 [service(65486)] [INFO] enabling systemd service
21:21:43 [service(65486)] [INFO] service registered correctly!
21:21:43 [service(65499)] [INFO] reading configs from: "/home/ryse/.config/espanso"
21:21:43 [service(65499)] [INFO] reading packages from: "/home/ryse/.config/espanso/match/packages"
21:21:43 [service(65499)] [INFO] using runtime dir: "/home/ryse/.cache/espanso"
21:21:43 [service(65499)] [INFO] system info: Fedora Linux v39 - kernel: 6.6.6-200.fc39.x86_64
21:21:43 [service(65499)] [ERROR] espanso is already running!
  ~ ❯  

**Setup information**
- OS: Fedora 39 on a dell latitude 5310, wayland
- Version:2.2.1

**Comment by smeech** [comment] 2023-12-18 16:49
Not entirely a Wayland issue. Here in Mint Xfce (X11), Espanso has accumulated ten Zombie processes which close with `espanso stop` `espanso start`, leaving three:
- /usr/bin/espanso launcher
- /usr/bin/espanso daemon
- /usr/bin/espanso worker --monitor-daemon

I thought that was normal!

**Comment by rysete** [comment] 2023-12-18 17:38
I don't know exactly how it works on xfce, but on gnome normally espanso works in background all time right?. With x11 or Wayland. (I've been use espanso gui because that, for triggers edition... etc)

**Comment by rysete** [comment] 2023-12-19 07:28
> I don't know exactly how it works on xfce, but on gnome normally espanso works in background all time right?. With x11 or Wayland. (I've been use espanso gui because that, for triggers edition... etc)

Espanso sync-tool is the main window of that app, searching about, that sync-tool keeps beeing a problem on wayland right?

**Comment by Lancaban** [comment] 2024-01-04 09:49
I've just now encountered this issue with the most recent update, been running espanso on wayland for a year now, without issue. 

As of the most recent update though, I noticed an extra running app in my taskbar, and it creates what seems to be a single pixel "window" that I can't get rid of. 

Any word on a solution for this one?

**Comment by iamkarlson** [comment] 2024-01-04 15:43
on a sway, this window titled as "Espanso Sync Tool". Not possible to close nor hide.

**Comment by Janov911** [comment] 2024-01-05 15:45
same issue here, both on ubunut 22.04 (VM) and Fedora 39 (bare metal)
The sync tool has an open window and cannot be closed.

**Comment by ronjouch** [comment] 2024-01-07 17:09
> I've just now encountered this issue with the most recent update, been running espanso on wayland for a year now, without issue.
> 
> As of the most recent update though, I noticed an extra running app in my taskbar, and it creates what seems to be a single pixel "window" that I can't get rid of.

I confirm this.

- Espanso 2.1.8 had no issue
- Espanso 2.2.1 shows this weird 10px-wide unclosable window named `Espanso Sync Tool`:

![espanso-sync-tool_weird-small-window](https://github.com/espanso/espanso/assets/522085/a4a442b2-d412-446e-8681-be4a8c2d5705)

Reading [Docs about sync](https://espanso.org/docs/sync/), it's something I don't need, and I couldn't find any [Espanso option](https://espanso.org/docs/configuration/options/) to disable it. Is there a way to disable it?

Arch Linux / GNOME Shell & Mutter 45.2 / Wayland 1.22.0

**Comment by morgan-dgk** [comment] 2024-01-10 15:28
Related to #1776. @ronjouch, the sync window is required under wayland to get keyboard state and is different to config synchronization (see comments on #976). 

I have been trying to investigate this issue further, but have not made much progress debugging where things are going wrong (presumably something to do with smithay-client-toolkit and communication with the wayland compositor).

**Comment by Lancaban** [comment] 2024-01-10 15:30
If there is any way I can help, logs I can provide, or anything like that I'd be happy to try, though I may need to be walked through the process. 

I love the app and am willing to put in the work, to help it out.

**Comment by morgan-dgk** [comment] 2024-01-10 15:40
@smeech propose closing this as a duplicate of #1776

**Comment by smeech** [comment] 2024-01-10 16:00
> @smeech propose closing this as a duplicate of #1776

Happy to agree - that seems to be the problem.

**Comment by smeech** [comment] 2024-01-10 16:00
-

**Closed as not planned by smeech** 2024-01-10 16:00 UTC
Labels: bug, Linux, wayland

**Comment by morgan-dgk** [comment] 2024-01-10 16:27
@Lancaban thank you for your kind offer of support. I think we have the relevant logs captured already, but I am no expert when it comes to the wayland protocol or wayland client libraries such as smithay-client-toolkit (which espanso relies on). 

If you happen to have any knowledge in these areas, then any help would be greatly appreciated!

**Comment by Lancaban** [comment] 2024-01-25 12:48
Sorry it took me so long to get back here. 

I'm not a developer or programmer of any sort, I['m just an enthusiastic Linux user.
It might be worth noting that I've been using Wayland for over a year, been using Espanso for almost as long. 

The window problem only showed up a few versions ago, for about 10+ months I ran espanso wayland without any issues, I think it was around 2.19 or so when it showed up? 

Not sure if that will make any difference, or help at all. 

For what it's worth, I'm running an Arch based Distro and installing through the AUR.

For anyone else, it's pretty easy to work around from a user end on KDE.
Right-click the icon in the task bar, then: 
 "keep below other windows" and then "minimize".
Also: to get really fancy, create a window rule to tell it to skip the task bar.

**Comment by KamilKleina** [comment] 2024-03-10 17:45
> Sorry it took me so long to get back here.
> 
> I'm not a developer or programmer of any sort, I['m just an enthusiastic Linux user. It might be worth noting that I've been using Wayland for over a year, been using Espanso for almost as long.
> 
> The window problem only showed up a few versions ago, for about 10+ months I ran espanso wayland without any issues, I think it was around 2.19 or so when it showed up?
> 
> Not sure if that will make any difference, or help at all.
> 
> For what it's worth, I'm running an Arch based Distro and installing through the AUR.
> 
> For anyone else, it's pretty easy to work around from a user end on KDE. Right-click the icon in the task bar, then: "keep below other windows" and then "minimize". Also: to get really fancy, create a window rule to tell it to skip the task bar.

Any chance you can tell what rule did you write for it? I am trying to use word "espanso" and substring but it doesn't work :(

**Comment by Lancaban** [comment] 2024-03-10 17:53
Right now I'm on KDE plasma 6 and can't screenshot/reproduce the steps exactly, originally it was a matter of right-clicking on it, in the task bar and selecting the option to create a rule for this window, that option seems to be not present in Plasma 6 however

**Comment by Lancaban** [comment] 2024-04-03 20:23
An update of sorts, today I installed using the espanso-Wayland-git package from the AUR instead of the standard espanso-Wayland package, and I am not having the above (or any other) issues any longer

**Comment by rysete** [comment] 2024-04-03 21:50
Here too, I've re-installed in the last week and just works

**Comment by morgan-dgk** [comment] 2024-04-04 15:09
Fixed by #1901
