### ISSUE TITLE
Replacement issue with Kitty

### ISSUE THREAD

**Issue by dufferzafar** [federico-terzi/espanso#281] opened 2020-05-14 15:34 UTC
I looked at existing issues, and even at the code. It seems there is some ["special" handling](https://github.com/federico-terzi/espanso/blob/279aace2bbaaaa4d273d53c11baa92ccc2306854/src/keyboard/linux.rs#L57) required for terminals. Can you please add [kitty](https://github.com/kovidgoyal/kitty/) to the list?

With a file like:

```yaml

matches:
  - trigger: ";name"
    replace: "Shadab Zafar"

  - trigger: ";email"
    replace: "hello@email.com"
```

Results in:

![Espanso on Kitty](https://user-images.githubusercontent.com/1449512/81954345-5f4c9700-9626-11ea-83e8-4c8ba2dd5a48.gif)

Notice the issues with case of the text as well as special characters like `@`.

**Comment by federico-terzi** [comment] 2020-05-14 17:55
This is pretty strange, as it should work correctly! Could you please try to add this line to your configuration and see if that helps?

```
fast_inject: false
```

**Comment by federico-terzi** [comment] 2020-06-09 19:12
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)

**Closed by federico-terzi** 2020-06-09 19:12 UTC
Labels: Linux, bug

**Comment by matclab** [comment] 2020-07-30 12:16
Still have some issues here with kitty 0.18.1 and espanso 0.6.3.

With default configuration file, `07/30/2020` expands to `àè:"à:éàéà` and with `fast_inject: false`, it expands to `)&>#)>@)@)`

**Comment by matclab** [comment] 2020-07-30 12:19
I wonder if `i3` doesn't do something in between because when trigerring an expansion in kitty terminal i3 shows me a somewhat unrelated error about duplicate keybinding or not being able to translate some keys.

**Comment by matclab** [comment] 2020-07-30 12:24
Hmmm it's not related to kitty, as I've the same behavior in xterm or gnome-terminal

**Comment by federico-terzi** [comment] 2020-07-31 11:19
@matclab I'm sorry you experienced this problem, what keyboard layout are you using? In the meanwhile, you can try setting:

```
backend: Clipboard
```

in your default.yml config

**Comment by matclab** [comment] 2020-07-31 11:31
Thanks for your help.
My layout is:
```
$setxkbmap -query 
rules:      evdev
model:      pc105
layout:     fr
variant:    oss
```

**Comment by federico-terzi** [comment] 2020-08-01 16:25
@matclab thank you. It seems like the non-English layouts have some problems on Terminals without the `Clipboard` backend

**Comment by ivanddm** [comment] 2021-02-28 07:00
Hi there,

I'm having this issue as well in kitty (Garuda Linux). `fast_inject: false` does solve the issue however the backspace feature, although it works as well, it add some characters to the initial trigger (basically it doesn't come back to the same trigger characters). Alacritty and Konsole terminals don't have this issue.

**Comment by federico-terzi** [comment] 2021-03-01 07:45
Hey @ivanddm,

I'm sorry you experienced this problem! Could you please try adding the `backspace_delay: 10` option in your default.yml file and see if that helps? You might also need to tweak that number.
If it does, then we can move it to an app-specific config so that it only affects Kitty. A good starting point is this discussion on VSCode: https://github.com/federico-terzi/espanso/issues/544#issuecomment-773229209

Cheers :)

**Comment by ivanddm** [comment] 2021-03-02 04:31
Thanks @federico-terzi. I will try that out, thanks a lot for your support.

In Mac, espanso is working beautifully (I'm gradually migrating from textexpander). However in Linux, besides the issue with Kitty (which might make me use a different default terminal, alacratty or konsole don't have such issues), I noticed as well that it takes a considerable amount of time to restart espanso (like a minute or so). It might be something in my config that is causing the issue, not sure.

Anyways, I will come back to you after trying the suggested `backspace_delay`.

**Comment by federico-terzi** [comment] 2021-03-02 19:55
> I noticed as well that it takes a considerable amount of time to restart espanso

Wow, this is unbearably slow! Espanso shouldn't take more than a second or two to restart, so there is something seriously wrong here :) 

How many matches do you have? Did you install any "big" package?

**Comment by ivanddm** [comment] 2021-03-04 20:44
@federico-terzi as suspected, it was something with my configuration, not sure what. I switched to another distro with i3wm and espanso is running smoothly and restarting right away, not delay whatsoever. Regarding Kitty, I don't think I will be using it in Linux, as Alacritty seems to work much better in Linux. So no problem from my side. Thanks in any case for following up :)

**Comment by federico-terzi** [comment] 2021-03-05 14:38
@ivanddm Great! No worries :) Feel free to point out any other issues as they occur!

**Comment by crisidev** [comment] 2022-03-18 17:52
Is it possible to reopen this? I am experiencing issue with replacement in Kitty 0.24.2 on ubuntu, where every replacement becomes a `v`.

I have tried to use the `backend: Clipboard` and `fast_inject: false`.

This is only happening on Kitty, other terminals work fine and the rest of windows work fine as well.

I am not sure how to debug this..

**Comment by crisidev** [comment] 2022-03-18 17:59
Is it possible to reopen this? I am experiencing issue with replacement in Kitty 0.24.2 on ubuntu, where every replacement becomes a `v`.

I have tried to use the `backend: Clipboard` and `fast_inject: false`.

This is only happening on Kitty, other terminals work fine and the rest of windows work fine as well.

I am not sure how to debug this..

**Comment by federico-terzi** [comment] 2022-03-19 09:38
@crisidev I'm sorry you experienced this problem! What version of Espanso are you running? Upgrading to the v2 might help: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

**Comment by crisidev** [comment] 2022-03-19 19:50
First of all thanks for this product! I am running espanso 2.1.3-alpha and the character that get printed is a literal `v`. I have disabled espanso for now on kitty by setting `backspace_delay` to a very high number, but I would like to be able to debug this 😞

**Comment by federico-terzi** [comment] 2022-03-23 19:11
@crisidev Thanks! That's interesting, what keyboard layout are you using? :)

**Comment by crisidev** [comment] 2022-03-23 19:15
Just qwerty with en-US

**Comment by federico-terzi** [comment] 2022-03-25 18:58
@matclab Thanks! One thing you might try is remapping the paste shortcut used by espanso when using Kitty. See also: https://espanso.org/docs/configuration/app-specific-configurations/

Create a file in `$CONFIG/config/kitty.yml` with this content:

```yaml
filter_class: "kitty"
paste_shortcut: "SHIFT+INSERT"
apply_patch: false
```

Let me know if that helps :)

**Comment by crisidev** [comment] 2022-03-28 08:44
First of all thanks for all the help you are giving me 😀

With the snippet above the `v` is not pasted anymore, espanso just delete the match.

So for example if I write `a'`, the 2 characters are just deleted.

**Comment by tissieres** [comment] 2022-03-29 06:52
Hello @federico-terzi,
Thanks for espanso!
I suffer from the same problem. I tried to set the `paste_shortcut` to `CTRL+SHIFT+V` since it is what is configured with my kitty, but it still output only a `v` in my prompt. Switching `backend` did not help.

**Comment by federico-terzi** [comment] 2022-04-03 17:56
@crisidev @tissieres Thank you guys, could you please try also adding this option? (increase the values as necessary)

```
pre_paste_delay: 500
```

If this still doesn't solve it, you might try installing the `xclip` utility (using your favorite package manager) and also adding this line:

```
x11_use_xclip_backend: true
```

Let me know if that helps :)

**Comment by tissieres** [comment] 2022-04-03 18:02
Thanks for coming back to us. Nope, neither `pre_paste_delay` nor `x11_use_xclip_backend` helped in my case. I'm gonna downgrade to the 0.7x in the meantime.

**Comment by 0range0range** [comment] 2022-07-17 15:20
I have similar problem. Also tried everything above.

**Comment by oaao** [comment] 2022-07-20 19:07
solved this at least for my use case by trying all the combinations for `.yml` config edits suggested so far until something dinged.

---

my solution:
```python
$CONFIG/
└── espanso/
    ├── user/
    │   └── kitty.yml  # MUST be in this subdirectory
    └── default.yml
```
```yml
# ~/.config/espanso/user/kitty.yml
filter_class: "kitty"

fast_inject: false

# backend: Clipboard            -- not necessary; actually seems more performant if omitted
# paste_shortcut: "ShiftInsert" -- no change with any accepted inputs ("CtrlShiftV", etc.)
# apply_patch: false            -- no change in any combination
```

the file placement + `fast_inject: false` was literally all i needed!

---

my initial conditions:
- `kitty` terminal
- my only custom espanso config was `user/kitty.yml` which specified only `backend: Clipboard`
- default keyboard layout
- all replacements in `kitty` outputting as the character `v`, like @tissieres & @crisidev 
- all other replacements functioning normally

**Comment by oaao** [comment] 2022-07-20 19:23
likely also relevant: `backend: Clipboard` could neither cause nor solve the problem on its own, but its interplay with `fast_inject` seems worth mentioning until i can take a proper look at this in a few days:

assuming `:espanso` -> `Hi there!` is the correctly functioning replacement,

- :x: -> `hi there1` (shift key?) produced by:
  - `espanso` defaults (no `user/kitty.yml`)
  - `fast_inject: true`, and no backend specification
- :x: -> `v` (ctrl+v?) both `fast_inject` & `backend: Clipboard` 
  -  both `fast_inject: true` and `backend: Clipboard`
  - (again, any combinations involving `paste_shortcut` + `apply_patch` produced no change)
- :x: -> `hi there1`
- :heavy_check_mark: `Hi there!`
  - `fast_inject: false` and `backend: Clipboard` (replacement is highlighted, but a bit awkward/sluggish on my machine)
  - `fast_inject: false`, and no backend specification (no highlight, but snappier for me)

**Comment by f0rdprefect** [comment] 2022-08-31 05:09
I get bitten by this bug right now and trying to figure out how to configure espanso correctly so I get the correct replacements. 

So far I just tried `fast_inject : false` and `backend : Clipboard` with no change in behavior. This is a pitty since I just switched from alacritty to kitty due to performance reasons...

**Comment by emilBeBri** [comment] 2022-09-10 22:21
same here - if I try to replace

> ,ae 

with the Danish char

> æ

it works fine in alacritty, but not in kitty. I think it's the problem of espanso, as you say. I tried using both backend clipboard and fast_inject, but it did not fix it. 

shame, I would prefer to use kitty! But I rely on espanso too much so that will have to wait till this is figured out. Please let me know if I can help troubleshoothing! (I'm without internet the next 14 days though)

**Comment by dudozermaks** [comment] 2022-09-28 13:40
same thing here. tried everything above - non of that helped. i'm using kitty + manjaro i3 + [espanso from AUR](https://aur.archlinux.org/packages/espanso). espanso works everywhere except kitty :(.
I have this in my base.yml:
```
- trigger: ":py_temp"
    replace: |
             # !/usr/bin/python3
             # {{mydate}}
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"
```
I have this in my default.yml:
```
backend: Inject
fast_inject: false
```
with backend 'Inject', it replaces this string: "3 1/usr/bin/python3". if i choose another backend, then espanso replaces it to 'v'

**Comment by nilp0inter** [comment] 2023-01-26 10:15
Hi,

I just want to report that I tried several combinations and this is the first one that works for me:

```yaml
backend: Clipboard
disable_x11_fast_inject: true
inject_delay: 15
key_delay: 10
```

Hope that helps.

Cheers!

**Comment by emilBeBri** [comment] 2023-01-30 14:29
That didn't work me, what @nilp0inter did.

would love to see a solution to this...!! (that is not hacky)

**Comment by Argus-Khan** [comment] 2023-08-17 16:49
Still having this issue, none of the solutions mentioned above work for me. Using Clipboard back-end simply expands to "v", otherwise using Inject back-end replaces some of the characters with different characters such as
: => ;
( => 9 
) => 0 
and etc...

**Setup:**
kitty 0.29.2
espanso 2.1.8
Fedora 38
i3 4.22

**Comment by emilBeBri** [comment] 2023-08-31 15:52
Thanks @back2analogue  for the clarification - I think kovids answer is a bit odd, since it works fine in alacritty. But I have read enough of his github comments to know that he's a gruff person and when he has set his mind on something it does not easily get unset. So that's that then. But good to know that there is no easy fix for this. 

Alacritty it is then, yes :)

**Comment by alperyilmaz** [comment] 2024-07-24 22:51
looks like there's still no fix for this.. that's sad (that the problem is kitty and it's not solvable).. I'm using gnome-terminal when I need  espanso in terminal..

**Comment by smeech** [comment] 2024-07-25 09:04
It's likely that one would have to persuade @kovidgoyal to take this on. He's closed the two Issues in [Kitty](https://github.com/kovidgoyal/kitty) - https://github.com/kovidgoyal/kitty/issues/4487 & https://github.com/kovidgoyal/kitty/issues/6895 as he doesn't have interest in fixing the problem, which is fair enough - it's his project. His suppositions about how Espanso works suggest he's not even looked at it. Any further representations would have to be made there, I'm afraid :disappointed: .

**Comment by BhaveshDiwan** [comment] 2024-09-25 21:21
[This](https://github.com/kovidgoyal/kitty/issues/4487#issuecomment-2078003959) worked for me. Quoting from original author:

I solve this issue in X11 by adding it to `.config/espanso/config/default.yml`:
```
disable_x11_fast_inject: true
```

**Comment by vctls** [comment] 2024-11-08 07:54
☝️ https://github.com/espanso/espanso/issues/281#issuecomment-2375285187

This is working as of Kitty v0.36.2 and Espanso v2.2.1 with X11.
Not sure if it has any drawbacks, though.

**Comment by alperyilmaz** [comment] 2024-11-08 12:27
Hi, @vctls  thanks for the notification but it still does not work me 

With espanso, I'm saving image from clipboard to images folder and then paste the markdown formatted link. Here's my trigger:
```
  - trigger: ":image"
    replace: "![]({{output}})"
    vars:
      - name: output
        type: shell
        params:
          cmd: "~/bin/paste_image_from_clipboard.sh"
```
          
My script is just printing image path with echo:
```
echo "images/$epoch.png"
```

If I run the script I get the following output:

```
$ ~/bin/paste_image_from_clipboard.sh
images/1731059584.png
```

But if I use espanso with ":image" trigger, I expect `![](images/1731059587.png)` however I get:
```
!89(images/1731059587.png)
```

Have latest version of Kitty. My espanso version and session info are below and I use `disable_x11_fast_inject: true` in my config :
```
$ echo $XDG_SESSION_TYPE
x11

$ kitty --version
kitty 0.37.0 created by Kovid Goyal

$ espanso --version
espanso 2.2.1

$ cat ~/.config/espanso/config/default.yml
disable_x11_fast_inject: true
```

I noticed there's rich text option (`markdown: '![]({{output}})'`), but it didnt work for me.

**Comment by jpmvferreira** [comment] 2026-05-05 20:23
Is there an equivalent workaround for users using Wayland instead of X11?
